export interface LiveExportRegressionFixturePair {
  readonly scenarioId: string;
  readonly scenarioDescription: string;
  readonly peerAAddr: string;
  readonly peerBAddr: string;
  readonly peerAExport: Record<string, unknown>;
  readonly peerBExport: Record<string, unknown>;
}

export const PHIL_KENNY_ONE_ON_ONE_76_PAIR: LiveExportRegressionFixturePair = {
  scenarioId: 'phil-kenny-one-on-one-76',
  scenarioDescription:
    'Captured paired export from the real phil-kenny one-on-one call that exposed mixed transport/stall pressure on one peer and severe stale-timestamp dropping on the other.',
  peerAAddr: 'peer-A',
  peerBAddr: 'peer-B',
  peerAExport: {
    liveMetricsSnapshot: {
      role: 'root-forwarder',
      packetsDroppedStaleTimestamp: 22,
      packetsDroppedPendingDecrypt: 0,
      pendingDecryptDepthHighWater: 0,
      jitterUnderruns: 0,
      missingFrames: 0,
      concealmentTicks: 130,
      avgPcmBufferedMs: 90.851,
      avgPlayoutDeltaMs: -29.149,
      playoutUnderTargetFraction: 0.481,
      playoutOutsideTargetFraction: 0.689,
      playoutRateFractionBelow1: 0.665,
      adaptiveNetworkMode: 'recovery',
      playoutStarvationWorstSeverity: 'none',
      gcallAudioStage5BoostCumulativeMs: 23_885,
      reticulumAudioBridgeQueuedFramesHighWater: 24,
      reticulumAudioBinaryOutQueueDepthHighWater: 2,
      reticulumAudioBridgeWaitingForDrain: false,
      reticulumAudioQueuePressureDrops: 13,
      reticulumAudioStaleDrops: 0,
    },
    exportWindowMetrics: {
      avgPcmBufferedMs: 0,
      avgPlayoutDeltaMs: 0,
      playoutUnderTargetFraction: 0,
      playoutOutsideTargetFraction: 0,
      playoutRateFractionBelow1: 0,
      jitterUnderruns: 0,
      missingFrames: 0,
      concealmentTicks: 0,
      packetsDroppedStaleTimestamp: 0,
      packetsDroppedPendingDecrypt: 0,
      packetsDroppedPendingDecryptRatePerSec: 0,
      pendingDecryptDepthHighWater: 0,
      reticulumAudioBridgeQueuedFramesHighWater: 0,
      reticulumAudioBinaryOutQueueDepthHighWater: 0,
      reticulumAudioQueuePressureDrops: 0,
      reticulumAudioStaleDrops: 0,
      avgOpusBufferedMs: 0,
      maxOpusBufferedMs: 0,
      adaptiveTargetMedianMs: 0,
      wasmFecDeferredPcmTicks: 0,
      durationMs: 30_938,
    },
    gcallPerfSnapshot: {
      meta: {
        tickBudgetBreachCount: 23,
        tickBudgetBreachP95Ms: 39.7,
        tickBudgetBreachMaxMs: 45.8,
      },
      longTasks: {
        count: 0,
      },
    },
    v2Diagnostics: {
      v2ManagedSourceAddrs: ['peer'],
      legacyWindowOpusMetricsMeaningful: false,
      avgJitterBufferedMs: 0,
      avgPcmRingBufferedMs: 74.71582557569819,
      avgTargetBufferMs: 120,
      events: [
        {
          schemaVersion: 2,
          kind: 'peer-health',
          wallClockMs: 196329.0999994278,
          payload: {
            sourceAddr: 'QP9Jj4…i6rP',
            level: 'recovering',
            evidenceExpiresAtMs: 199328.29999923706,
            observedAtMs: 196328.29999923706,
            freshLocalMediaConfirmed: false,
            activeEvidenceCount: 1,
          },
        },
        {
          schemaVersion: 2,
          kind: 'transport-evidence',
          wallClockMs: 196329.39999961853,
          payload: {
            kind: 'path-warming',
            sourceAddr: 'QP9Jj4…i6rP',
            observedAtMs: 196328.29999923706,
            expiresAtMs: 196329.29999923706,
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 197661.0999994278,
          payload: {
            fromState: 'coldStart',
            toState: 'steady',
            reason: 'jitter-filled-to-start-threshold',
            atMs: 1776982184538,
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1987934180',
            policyOutput: {
              maxDecodePerTick: 3,
              targetBufferMs: 120,
            },
          },
        },
        {
          schemaVersion: 2,
          kind: 'jitter-stats',
          wallClockMs: 197704.69999980927,
          payload: {
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1987934180',
            depth: 13,
            bufferedMs: 260,
            lastPushAgeMs: 247.10000038146973,
            state: 'steady',
          },
        },
        {
          schemaVersion: 2,
          kind: 'pcm-ring-stats',
          wallClockMs: 197704.69999980927,
          payload: {
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1987934180',
            bufferedMs: 0,
            underruns: 0,
            overruns: 0,
            state: 'steady',
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 197705.0999994278,
          payload: {
            fromState: 'steady',
            toState: 'backlogDrain',
            reason: 'pcm-deficit:pcm=0ms,opus=260ms',
            atMs: 1776982184584,
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1987934180',
            policyOutput: {
              maxDecodePerTick: 8,
              targetBufferMs: 120,
            },
          },
        },
        {
          schemaVersion: 2,
          kind: 'jitter-stats',
          wallClockMs: 197705.79999923706,
          payload: {
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1987934180',
            depth: 5,
            bufferedMs: 100,
            lastPushAgeMs: 248.19999980926514,
            state: 'backlogDrain',
          },
        },
        {
          schemaVersion: 2,
          kind: 'pcm-ring-stats',
          wallClockMs: 197705.79999923706,
          payload: {
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1987934180',
            bufferedMs: 0,
            underruns: 0,
            overruns: 0,
            state: 'backlogDrain',
          },
        },
      ],
    },
  },
  peerBExport: {
    liveMetricsSnapshot: {
      role: 'standby-forwarder',
      packetsDroppedStaleTimestamp: 947,
      packetsDroppedPendingDecrypt: 0,
      pendingDecryptDepthHighWater: 0,
      jitterUnderruns: 3,
      missingFrames: 10,
      concealmentTicks: 566,
      avgPcmBufferedMs: 110.566,
      avgPlayoutDeltaMs: -21.946,
      playoutUnderTargetFraction: 0.538,
      playoutOutsideTargetFraction: 0.975,
      playoutRateFractionBelow1: 0.559,
      adaptiveNetworkMode: 'recovery',
      playoutStarvationWorstSeverity: 'none',
      gcallAudioStage5BoostCumulativeMs: 23_999,
      reticulumAudioBridgeQueuedFramesHighWater: 10,
      reticulumAudioBinaryOutQueueDepthHighWater: 2,
      reticulumAudioBridgeWaitingForDrain: false,
      reticulumAudioQueuePressureDrops: 0,
      reticulumAudioStaleDrops: 0,
    },
    exportWindowMetrics: {
      avgPcmBufferedMs: 0,
      avgPlayoutDeltaMs: 0,
      playoutUnderTargetFraction: 0,
      playoutOutsideTargetFraction: 0,
      playoutRateFractionBelow1: 0,
      jitterUnderruns: 0,
      missingFrames: 0,
      concealmentTicks: 0,
      packetsDroppedStaleTimestamp: 0,
      packetsDroppedPendingDecrypt: 0,
      packetsDroppedPendingDecryptRatePerSec: 0,
      pendingDecryptDepthHighWater: 0,
      reticulumAudioBridgeQueuedFramesHighWater: 0,
      reticulumAudioBinaryOutQueueDepthHighWater: 0,
      reticulumAudioQueuePressureDrops: 0,
      reticulumAudioStaleDrops: 0,
      avgOpusBufferedMs: 0,
      maxOpusBufferedMs: 0,
      adaptiveTargetMedianMs: 0,
      wasmFecDeferredPcmTicks: 17,
      durationMs: 29_168,
    },
    gcallPerfSnapshot: {
      meta: {
        tickBudgetBreachCount: 0,
        tickBudgetBreachP95Ms: 0,
        tickBudgetBreachMaxMs: 0,
      },
      longTasks: {
        count: 0,
      },
    },
    v2Diagnostics: {
      v2ManagedSourceAddrs: ['peer'],
      legacyWindowOpusMetricsMeaningful: false,
      avgJitterBufferedMs: 214.28,
      avgPcmRingBufferedMs: 37.891373801916934,
      avgTargetBufferMs: 120,
      events: [
        {
          schemaVersion: 2,
          kind: 'peer-health',
          wallClockMs: 261126.59999996424,
          payload: {
            sourceAddr: 'QTSzRS…9jMn',
            level: 'recovering',
            evidenceExpiresAtMs: 264126.1999999881,
            observedAtMs: 261126.29999995232,
            freshLocalMediaConfirmed: false,
            activeEvidenceCount: 1,
          },
        },
        {
          schemaVersion: 2,
          kind: 'transport-evidence',
          wallClockMs: 261126.79999995232,
          payload: {
            kind: 'path-warming',
            sourceAddr: 'QTSzRS…9jMn',
            observedAtMs: 261126.19999998808,
            expiresAtMs: 261127.19999998808,
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 261215.69999998808,
          payload: {
            fromState: 'coldStart',
            toState: 'steady',
            reason: 'jitter-filled-to-start-threshold',
            atMs: 1776982185294,
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:3553810156',
            policyOutput: {
              maxDecodePerTick: 3,
              targetBufferMs: 120,
            },
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 261423.29999995232,
          payload: {
            fromState: 'steady',
            toState: 'backlogDrain',
            reason: 'pcm-deficit:pcm=0ms,opus=320ms',
            atMs: 1776982185502,
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:3553810156',
            policyOutput: {
              maxDecodePerTick: 8,
              targetBufferMs: 120,
            },
          },
        },
        {
          schemaVersion: 2,
          kind: 'jitter-stats',
          wallClockMs: 261649.69999998808,
          payload: {
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:3553810156',
            depth: 3,
            bufferedMs: 60,
            lastPushAgeMs: 115.10000002384186,
            state: 'backlogDrain',
          },
        },
        {
          schemaVersion: 2,
          kind: 'pcm-ring-stats',
          wallClockMs: 261649.69999998808,
          payload: {
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:3553810156',
            bufferedMs: 240,
            underruns: 0,
            overruns: 0,
            state: 'backlogDrain',
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 261650.79999995232,
          payload: {
            fromState: 'backlogDrain',
            toState: 'steady',
            reason: 'pcm-latency-cap:pcm=220ms',
            atMs: 1776982185729,
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:3553810156',
            policyOutput: {
              maxDecodePerTick: 3,
              targetBufferMs: 120,
            },
          },
        },
      ],
    },
  },
};

export const PHIL_KENNY_ONE_ON_ONE_77_PAIR: LiveExportRegressionFixturePair = {
  scenarioId: 'phil-kenny-one-on-one-77',
  scenarioDescription:
    'Captured paired export from the post-fix phil-kenny one-on-one call: the root-forwarder still shows residual stall/playout instability while the standby-forwarder is mostly healthy aside from timestamp dropping.',
  peerAAddr: 'peer-A',
  peerBAddr: 'peer-B',
  peerAExport: {
    liveMetricsSnapshot: {
      role: 'root-forwarder',
      packetsDroppedStaleTimestamp: 0,
      packetsDroppedPendingDecrypt: 0,
      pendingDecryptDepthHighWater: 0,
      jitterUnderruns: 0,
      missingFrames: 0,
      concealmentTicks: 25,
      avgPcmBufferedMs: 132.748,
      avgPlayoutDeltaMs: 12.748,
      playoutUnderTargetFraction: 0.217,
      playoutOutsideTargetFraction: 0.597,
      playoutRateFractionBelow1: 0.41,
      adaptiveNetworkMode: 'recovery',
      playoutStarvationWorstSeverity: 'none',
      gcallAudioStage5BoostCumulativeMs: 12_065,
      reticulumAudioBridgeQueuedFramesHighWater: 15,
      reticulumAudioBinaryOutQueueDepthHighWater: 3,
      reticulumAudioBridgeWaitingForDrain: false,
      reticulumAudioQueuePressureDrops: 0,
      reticulumAudioStaleDrops: 0,
    },
    exportWindowMetrics: {
      avgPcmBufferedMs: 0,
      avgPlayoutDeltaMs: 0,
      playoutUnderTargetFraction: 0,
      playoutOutsideTargetFraction: 0,
      playoutRateFractionBelow1: 0,
      jitterUnderruns: 0,
      missingFrames: 0,
      concealmentTicks: 0,
      packetsDroppedStaleTimestamp: 0,
      packetsDroppedPendingDecrypt: 0,
      packetsDroppedPendingDecryptRatePerSec: 0,
      pendingDecryptDepthHighWater: 0,
      reticulumAudioBridgeQueuedFramesHighWater: 0,
      reticulumAudioBinaryOutQueueDepthHighWater: 0,
      reticulumAudioQueuePressureDrops: 0,
      reticulumAudioStaleDrops: 0,
      avgOpusBufferedMs: 0,
      maxOpusBufferedMs: 0,
      adaptiveTargetMedianMs: 0,
      wasmFecDeferredPcmTicks: 0,
      durationMs: 49_220,
    },
    gcallPerfSnapshot: {
      meta: {
        tickBudgetBreachCount: 17,
        tickBudgetBreachP95Ms: 24.8,
        tickBudgetBreachMaxMs: 24.8,
      },
      longTasks: {
        count: 0,
      },
    },
    v2Diagnostics: {
      v2ManagedSourceAddrs: ['peer'],
      legacyWindowOpusMetricsMeaningful: false,
      avgJitterBufferedMs: 106.95431472081218,
      avgPcmRingBufferedMs: 190.21392313270485,
      avgTargetBufferMs: 120,
      events: [
        {
          schemaVersion: 2,
          kind: 'peer-health',
          wallClockMs: 386049.10000038147,
          payload: {
            sourceAddr: 'QP9Jj4…i6rP',
            level: 'recovering',
            evidenceExpiresAtMs: 389048.5,
            observedAtMs: 386048.70000076294,
            freshLocalMediaConfirmed: false,
            activeEvidenceCount: 1,
          },
        },
        {
          schemaVersion: 2,
          kind: 'transport-evidence',
          wallClockMs: 386049.20000076294,
          payload: {
            kind: 'path-warming',
            sourceAddr: 'QP9Jj4…i6rP',
            observedAtMs: 386048.5,
            expiresAtMs: 386049.5,
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 387635.80000019073,
          payload: {
            fromState: 'coldStart',
            toState: 'steady',
            reason: 'jitter-filled-to-start-threshold',
            atMs: 1777059240690,
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1133259095',
            policyOutput: {
              maxDecodePerTick: 3,
              targetBufferMs: 120,
            },
          },
        },
        {
          schemaVersion: 2,
          kind: 'jitter-stats',
          wallClockMs: 387639.20000076294,
          payload: {
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1133259095',
            depth: 2,
            bufferedMs: 40,
            lastPushAgeMs: 4.700000762939453,
            state: 'steady',
          },
        },
        {
          schemaVersion: 2,
          kind: 'pcm-ring-stats',
          wallClockMs: 387639.20000076294,
          payload: {
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1133259095',
            bufferedMs: 0,
            underruns: 0,
            overruns: 0,
            state: 'steady',
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 387648.9000005722,
          payload: {
            fromState: 'steady',
            toState: 'backlogDrain',
            reason: 'pcm-deficit:pcm=0ms,opus=160ms',
            atMs: 1777059240703,
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1133259095',
            policyOutput: {
              maxDecodePerTick: 8,
              targetBufferMs: 120,
            },
          },
        },
        {
          schemaVersion: 2,
          kind: 'jitter-stats',
          wallClockMs: 395200,
          payload: {
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1133259095',
            depth: 12,
            bufferedMs: 240,
            lastPushAgeMs: 88,
            state: 'steady',
          },
        },
        {
          schemaVersion: 2,
          kind: 'pcm-ring-stats',
          wallClockMs: 395200.2,
          payload: {
            streamKey: 'QP9Jj4S3jpCgvPnaABMx8VWzND3qpji6rP:1:1133259095',
            bufferedMs: 220,
            underruns: 0,
            overruns: 0,
            state: 'steady',
          },
        },
      ],
    },
  },
  peerBExport: {
    liveMetricsSnapshot: {
      role: 'standby-forwarder',
      packetsDroppedStaleTimestamp: 220,
      packetsDroppedPendingDecrypt: 0,
      pendingDecryptDepthHighWater: 0,
      jitterUnderruns: 0,
      missingFrames: 0,
      concealmentTicks: 5,
      avgPcmBufferedMs: 146.437,
      avgPlayoutDeltaMs: 26.437,
      playoutUnderTargetFraction: 0.03,
      playoutOutsideTargetFraction: 0.392,
      playoutRateFractionBelow1: 0.075,
      adaptiveNetworkMode: 'low-latency',
      playoutStarvationWorstSeverity: 'none',
      gcallAudioStage5BoostCumulativeMs: 0,
      reticulumAudioBridgeQueuedFramesHighWater: 3,
      reticulumAudioBinaryOutQueueDepthHighWater: 1,
      reticulumAudioBridgeWaitingForDrain: false,
      reticulumAudioQueuePressureDrops: 0,
      reticulumAudioStaleDrops: 0,
    },
    exportWindowMetrics: {
      avgPcmBufferedMs: 0,
      avgPlayoutDeltaMs: 0,
      playoutUnderTargetFraction: 0,
      playoutOutsideTargetFraction: 0,
      playoutRateFractionBelow1: 0,
      jitterUnderruns: 0,
      missingFrames: 0,
      concealmentTicks: 0,
      packetsDroppedStaleTimestamp: 0,
      packetsDroppedPendingDecrypt: 0,
      packetsDroppedPendingDecryptRatePerSec: 0,
      pendingDecryptDepthHighWater: 0,
      reticulumAudioBridgeQueuedFramesHighWater: 0,
      reticulumAudioBinaryOutQueueDepthHighWater: 0,
      reticulumAudioQueuePressureDrops: 0,
      reticulumAudioStaleDrops: 0,
      avgOpusBufferedMs: 0,
      maxOpusBufferedMs: 0,
      adaptiveTargetMedianMs: 0,
      wasmFecDeferredPcmTicks: 0,
      durationMs: 52_355,
    },
    gcallPerfSnapshot: {
      meta: {
        tickBudgetBreachCount: 0,
        tickBudgetBreachP95Ms: 0,
        tickBudgetBreachMaxMs: 0,
      },
      longTasks: {
        count: 0,
      },
    },
    v2Diagnostics: {
      v2ManagedSourceAddrs: ['peer'],
      legacyWindowOpusMetricsMeaningful: false,
      avgJitterBufferedMs: 103.22370936902486,
      avgPcmRingBufferedMs: 202.63862332695984,
      avgTargetBufferMs: 120,
      events: [
        {
          schemaVersion: 2,
          kind: 'peer-health',
          wallClockMs: 372006.39999997616,
          payload: {
            sourceAddr: 'QTSzRS…9jMn',
            level: 'recovering',
            evidenceExpiresAtMs: 375005.89999997616,
            observedAtMs: 372006,
            freshLocalMediaConfirmed: false,
            activeEvidenceCount: 1,
          },
        },
        {
          schemaVersion: 2,
          kind: 'transport-evidence',
          wallClockMs: 372006.39999997616,
          payload: {
            kind: 'path-warming',
            sourceAddr: 'QTSzRS…9jMn',
            observedAtMs: 372005.89999997616,
            expiresAtMs: 372006.89999997616,
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 372088.10000002384,
          payload: {
            fromState: 'coldStart',
            toState: 'steady',
            reason: 'jitter-filled-to-start-threshold',
            atMs: 1777059239727,
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:749703133',
            policyOutput: {
              maxDecodePerTick: 3,
              targetBufferMs: 120,
            },
          },
        },
        {
          schemaVersion: 2,
          kind: 'state-transition',
          wallClockMs: 372088.7000000477,
          payload: {
            fromState: 'steady',
            toState: 'backlogDrain',
            reason: 'pcm-deficit:pcm=0ms,opus=100ms',
            atMs: 1777059239728,
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:749703133',
            policyOutput: {
              maxDecodePerTick: 8,
              targetBufferMs: 120,
            },
          },
        },
        {
          schemaVersion: 2,
          kind: 'jitter-stats',
          wallClockMs: 372328,
          payload: {
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:749703133',
            depth: 8,
            bufferedMs: 160,
            lastPushAgeMs: 92,
            state: 'backlogDrain',
          },
        },
        {
          schemaVersion: 2,
          kind: 'pcm-ring-stats',
          wallClockMs: 372328.10000002384,
          payload: {
            streamKey: 'QTSzRSxALCc6TCX9NNELj3oLtRMtKp9jMn:1:749703133',
            bufferedMs: 200,
            underruns: 0,
            overruns: 0,
            state: 'backlogDrain',
          },
        },
      ],
    },
  },
};
