/**
 * useGroupVoiceCall — decentralized group voice call hook.
 *
 * Architecture:
 *   ≤10 participants → single elected forwarder
 *   11–50 participants → hierarchical: cluster forwarders + root forwarder
 *
 * Audio pipeline:
 *   Microphone → CaptureWorkletNode (audio-worklet thread, VAD + 960-sample framing)
 *   → port.postMessage { frame, vad } → AudioEncoder (Opus 20kbps, main thread)
 *   → packet framing (addr+seq+vad+ts+nacl.secretbox) → DataChannel to forwarder
 *   Forwarder → decrypt-reencrypt skipped; forwarder routes encrypted bytes only
 *   Receiver → DataChannel ← forwarder → jitter buffer (20ms drain) → AudioDecoder (Opus)
 *   → PlaybackWorkletNode per speaker (audio-worklet thread, ring-buffer playback)
 *
 * Forwarder election (deterministic, same result on all peers):
 *   Sort participants by sha256(address + roomId) → lowest = root, 2nd = standby
 *   For ≥11: partition sorted list in groups of 10, lowest-in-group = cluster forwarder
 *
 * Security:
 *   Room media key: 32-byte random key generated by initiator
 *   Distributed via window.groupCall.sendKey() using nacl.box encryption per recipient
 *   Audio frames encrypted with nacl.secretbox(opusFrame, nonce, roomKey)
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { useAtomValue } from 'jotai';
import { userInfoAtom } from '../atoms/global';
import nacl from '../encryption/nacl-fast';
import ed2curve from '../encryption/ed2curve';
import AudioDecryptWorker from '../workers/audio-decrypt.worker?worker';

// ── Types ──────────────────────────────────────────────────────────────────────

export type RoomState = 'idle' | 'joining' | 'connected' | 'ended';
export type MyRole = 'participant' | 'cluster-forwarder' | 'root-forwarder' | 'standby-forwarder';
export type TopologyLabel = 'SFU' | 'Hierarchical';

export interface ClusterDef {
  members: string[];
  forwarder: string;
  standby: string;
}

export interface GroupTopology {
  topologyEpoch: number;
  rootForwarder: string;
  standbyForwarder: string;
  clusters: ClusterDef[];
}

export interface Participant {
  address: string;
  publicKey: string;
  speaking: boolean;
  role: MyRole;
}

// ── Constants ──────────────────────────────────────────────────────────────────

const OPUS_SAMPLE_RATE = 48000;
const OPUS_CHANNELS = 1;
const OPUS_BITRATE = 20_000;
const OPUS_FRAME_DURATION_MS = 20;
const OPUS_FRAME_SAMPLES = (OPUS_SAMPLE_RATE * OPUS_FRAME_DURATION_MS) / 1000; // 960

const JITTER_BUFFER_SIZE = 4;        // ~80ms buffer
const JITTER_DRAIN_INTERVAL_MS = 20; // drain every 20ms (one Opus frame)

const FORWARDER_TIMEOUT_MS = 3_000;  // miss 3 heartbeats → dead
const TOPOLOGY_HEARTBEAT_MS = 1_000; // forwarder sends GC_TOPOLOGY heartbeat
const PROMOTION_COOLDOWN_MS = 2_000; // standby waits before promoting

const CLUSTER_SIZE = 10;
const MAX_ACTIVE_SPEAKERS_LOCAL = 2;
const MAX_ACTIVE_SPEAKERS_GLOBAL = 3;

/** Minimum ms between P2P relay sends to the same peer while their DataChannel
 *  is still negotiating.  Caps relay IPC at ~5 frames/s instead of 50 Hz so the
 *  renderer is not flooded during the 1–5 s WebRTC negotiation window. */
const RELAY_MIN_INTERVAL_MS = 200;

const HEADER_LEN_OFFSET = 0;
const HEADER_ADDR_OFFSET = 1;
// After addr: [1 byte VAD][2 bytes seq][4 bytes timestamp][variable nacl.secretbox payload]

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Encode a Uint8Array to base64 without spreading into function arguments.
 *  btoa(String.fromCharCode(...bytes)) is O(n) on the call stack and causes
 *  excessive GC pressure at 50 Hz; this loop avoids the spread entirely. */
function uint8ToBase64(bytes: Uint8Array): string {
  let s = '';
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}

/** Decode a base64 string to a Uint8Array without Uint8Array.from + callback.
 *  Uint8Array.from(atob(b64), c => c.charCodeAt(0)) allocates an intermediate
 *  decoded string and iterates character-by-character via a closure; this loop
 *  reuses the pre-decoded string directly. */
function base64ToUint8(b64: string): Uint8Array {
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

/** Parse the plaintext header of an audio packet without performing crypto.
 *  Used to extract routing metadata (sourceAddr, vad, seq) for forwarding
 *  decisions before the packet is handed to the decrypt Worker.
 *  Format: [1B addrLen][addrBytes][1B vad][2B seq][4B ts][...rest] */
function parsePacketHeader(buf: Uint8Array): {
  sourceAddr: string;
  vad: boolean;
  seq: number;
  timestampMs: number;
} | null {
  try {
    let off = 0;
    const addrLen = buf[off++];
    if (addrLen === 0 || addrLen > 100) return null;
    const sourceAddr = new TextDecoder().decode(buf.slice(off, off + addrLen));
    off += addrLen;
    const vad = buf[off++] === 1;
    const seq = (buf[off++] << 8) | buf[off++];
    const timestampMs =
      (buf[off++] << 24) | (buf[off++] << 16) | (buf[off++] << 8) | buf[off++];
    return { sourceAddr, vad, seq, timestampMs };
  } catch {
    return null;
  }
}

/** sha256 → Uint8Array. Used for deterministic election. */
async function sha256Bytes(input: string): Promise<Uint8Array> {
  const enc = new TextEncoder();
  const buf = await crypto.subtle.digest('SHA-256', enc.encode(input));
  return new Uint8Array(buf);
}

/** Compare two Uint8Arrays lexicographically. */
function compareBytes(a: Uint8Array, b: Uint8Array): number {
  for (let i = 0; i < Math.min(a.length, b.length); i++) {
    if (a[i] < b[i]) return -1;
    if (a[i] > b[i]) return 1;
  }
  return a.length - b.length;
}

/** Compute election scores for all participants. Returns sorted list (lowest score first). */
async function computeElectionOrder(addresses: string[], roomId: string): Promise<string[]> {
  const scores = await Promise.all(
    addresses.map(async (addr) => ({
      addr,
      score: await sha256Bytes(addr + ':' + roomId),
    }))
  );
  scores.sort((a, b) => compareBytes(a.score, b.score));
  return scores.map((s) => s.addr);
}

/** Build topology from a sorted participant list. */
function buildTopology(
  sorted: string[],
  topologyEpoch: number
): GroupTopology {
  if (sorted.length <= CLUSTER_SIZE) {
    return {
      topologyEpoch,
      rootForwarder: sorted[0] ?? '',
      standbyForwarder: sorted[1] ?? '',
      clusters: [
        {
          members: sorted,
          forwarder: sorted[0] ?? '',
          standby: sorted[1] ?? '',
        },
      ],
    };
  }

  // Hierarchical: cluster forwarders + root
  const clusters: ClusterDef[] = [];
  for (let i = 0; i < sorted.length; i += CLUSTER_SIZE) {
    const chunk = sorted.slice(i, i + CLUSTER_SIZE);
    clusters.push({
      members: chunk,
      forwarder: chunk[0],
      standby: chunk[1] ?? chunk[0],
    });
  }

  // Root forwarder is the cluster forwarder with the lowest overall score
  const clusterForwarders = clusters.map((c) => c.forwarder);
  const rootForwarder = clusterForwarders[0];
  const standbyForwarder = clusterForwarders[1] ?? clusterForwarders[0];

  return { topologyEpoch, rootForwarder, standbyForwarder, clusters };
}

/** Determine this node's role given a topology. */
function computeMyRole(myAddress: string, topology: GroupTopology): MyRole {
  if (myAddress === topology.rootForwarder) return 'root-forwarder';
  if (myAddress === topology.standbyForwarder) return 'standby-forwarder';
  for (const cluster of topology.clusters) {
    if (myAddress === cluster.forwarder) return 'cluster-forwarder';
  }
  return 'participant';
}

/** Find which cluster forwarder a participant should send to. */
function findAssignedForwarder(myAddress: string, topology: GroupTopology): string {
  for (const cluster of topology.clusters) {
    if (cluster.members.includes(myAddress)) {
      return cluster.forwarder;
    }
  }
  return topology.rootForwarder;
}

/** Encode packet header + nacl.secretbox payload.
 *  Format: [1B addrLen][addrBytes][1B vad][2B seq][4B ts][24B nonce][ciphertext]
 */
function encodePacket(
  sourceAddr: string,
  vad: boolean,
  seq: number,
  timestampMs: number,
  opusFrame: Uint8Array,
  roomKey: Uint8Array
): Uint8Array {
  const addrBytes = new TextEncoder().encode(sourceAddr);
  const addrLen = addrBytes.length;

  const nonce = nacl.randomBytes(24);
  const ciphertext = nacl.secretbox(opusFrame, nonce, roomKey);

  const total = 1 + addrLen + 1 + 2 + 4 + 24 + ciphertext.length;
  const buf = new Uint8Array(total);
  let off = 0;

  buf[off++] = addrLen;
  buf.set(addrBytes, off); off += addrLen;
  buf[off++] = vad ? 1 : 0;
  buf[off++] = (seq >> 8) & 0xff;
  buf[off++] = seq & 0xff;
  buf[off++] = (timestampMs >>> 24) & 0xff;
  buf[off++] = (timestampMs >>> 16) & 0xff;
  buf[off++] = (timestampMs >>> 8) & 0xff;
  buf[off++] = timestampMs & 0xff;
  buf.set(nonce, off); off += 24;
  buf.set(ciphertext, off);

  return buf;
}

/** Decode packet. Returns null if decryption fails. */
function decodePacket(
  buf: Uint8Array,
  roomKey: Uint8Array
): { sourceAddr: string; vad: boolean; seq: number; timestampMs: number; opusFrame: Uint8Array } | null {
  try {
    let off = 0;
    const addrLen = buf[off++];
    const sourceAddr = new TextDecoder().decode(buf.slice(off, off + addrLen)); off += addrLen;
    const vad = buf[off++] === 1;
    const seq = (buf[off++] << 8) | buf[off++];
    const timestampMs = (buf[off++] << 24) | (buf[off++] << 16) | (buf[off++] << 8) | buf[off++];
    const nonce = buf.slice(off, off + 24); off += 24;
    const ciphertext = buf.slice(off);
    const plaintext = nacl.secretbox.open(ciphertext, nonce, roomKey);
    if (!plaintext) return null;
    return { sourceAddr, vad, seq, timestampMs, opusFrame: plaintext };
  } catch {
    return null;
  }
}

/** Convert Float32 PCM to Int16 PCM for WebCodecs AudioData. */
function float32ToInt16(f32: Float32Array): Int16Array {
  const i16 = new Int16Array(f32.length);
  for (let i = 0; i < f32.length; i++) {
    i16[i] = Math.max(-32768, Math.min(32767, Math.round(f32[i] * 32767)));
  }
  return i16;
}

/**
 * Sign fields for group call messages.
 * Delegates to the background process (which holds the private key) via
 * the same 'signPresenceMessage' IPC used by useP2PChat and presence.
 * The background performs: sort keys → JSON.stringify → Ed25519 → Base58.
 */
async function signGroupCallFields(
  fields: Record<string, unknown>
): Promise<string> {
  const result = await (window as any).sendMessage('signPresenceMessage', fields, 10_000);
  if (result?.error) throw new Error(String(result.error));
  if (typeof result?.signature !== 'string') throw new Error('signPresenceMessage returned no signature');
  return result.signature as string;
}

// ── Jitter buffer ──────────────────────────────────────────────────────────────

interface JitterEntry {
  seq: number;
  opusFrame: Uint8Array;
  receivedAt: number;
}

class JitterBuffer {
  private entries: JitterEntry[] = [];
  private lastPlayedSeq = -1;

  push(seq: number, opusFrame: Uint8Array): void {
    if (seq <= this.lastPlayedSeq) return; // already played or older
    if (this.entries.some((e) => e.seq === seq)) return; // duplicate
    this.entries.push({ seq, opusFrame, receivedAt: performance.now() });
    this.entries.sort((a, b) => a.seq - b.seq);
    if (this.entries.length > JITTER_BUFFER_SIZE * 2) {
      this.entries = this.entries.slice(-JITTER_BUFFER_SIZE * 2);
    }
  }

  /** Returns next frame to play, or null if buffer not ready. */
  pop(): Uint8Array | null {
    if (this.entries.length < JITTER_BUFFER_SIZE) return null;
    const entry = this.entries.shift();
    if (!entry) return null;
    this.lastPlayedSeq = entry.seq;
    return entry.opusFrame;
  }

  clear(): void {
    this.entries = [];
    this.lastPlayedSeq = -1;
  }
}

// ── DataChannel manager ────────────────────────────────────────────────────────

interface PeerConnection {
  pc: RTCPeerConnection;
  dc: RTCDataChannel | null;
  address: string;
  connId: string;
  role: 'upstream' | 'downstream' | 'backbone';
}

// ── Main hook ──────────────────────────────────────────────────────────────────

export function useGroupVoiceCall() {
  const userInfo = useAtomValue(userInfoAtom);

  // ── Room state ──────────────────────────────────────────────────────────────

  const [roomState, setRoomState] = useState<RoomState>('idle');
  const [participants, setParticipants] = useState<Participant[]>([]);
  const [myRole, setMyRole] = useState<MyRole>('participant');
  const [activeSpeakers, setActiveSpeakers] = useState<string[]>([]);
  const [topologyLabel, setTopologyLabel] = useState<TopologyLabel>('SFU');

  // ── Refs ────────────────────────────────────────────────────────────────────

  const roomIdRef = useRef<string>('');
  const chatIdRef = useRef<string>('');

  // Room key (32-byte symmetric key)
  const roomKeyRef = useRef<Uint8Array | null>(null);
  // Was I the one who generated the key? (initiator)
  const isInitiatorRef = useRef(false);

  // Topology state
  const topologyRef = useRef<GroupTopology | null>(null);
  const localEpochRef = useRef<number>(0);
  const myRoleRef = useRef<MyRole>('participant');
  const participantsRef = useRef<Map<string, { publicKey: string }>>(new Map());

  // Audio
  const audioContextRef = useRef<AudioContext | null>(null);
  const micStreamRef = useRef<MediaStream | null>(null);
  const captureWorkletRef = useRef<AudioWorkletNode | null>(null);
  const playbackWorkletsRef = useRef<Map<string, AudioWorkletNode>>(new Map());
  const encoderRef = useRef<AudioEncoder | null>(null);

  // VAD speaking flag — set from the capture worklet's port message
  const isSpeakingRef = useRef(false);
  // Mute: when true, both sendEncodedFrame and the capture worklet gate output
  const mutedRef = useRef(false);

  // Per-source decoders and jitter buffers
  const decoderMapRef = useRef<Map<string, AudioDecoder>>(new Map());
  const jitterMapRef = useRef<Map<string, JitterBuffer>>(new Map());
  const lastRecvAtRef = useRef<Map<string, number>>(new Map());

  // Outgoing seq counter per source
  const seqRef = useRef<number>(0);

  // Speaker tracking (for VAD-based active speaker selection)
  const localSpeakersRef = useRef<Map<string, number>>(new Map()); // addr → lastVadTime
  const speakerDrainTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // WebRTC peer connections
  const peerConnectionsRef = useRef<Map<string, PeerConnection>>(new Map());

  // Upstream DC to assigned forwarder
  const upstreamDCRef = useRef<RTCDataChannel | null>(null);
  // Standby DC (pre-connected)
  const standbyDCRef = useRef<RTCDataChannel | null>(null);

  // Forwarder heartbeat timer (for sending topology heartbeats)
  const topologyHeartbeatTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  // Standby promotion timer
  const promotionTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Last time we saw a topology heartbeat from root
  const lastRootHeartbeatRef = useRef<number>(Date.now());
  // Forwarder-timeout polling interval (runs every 500ms)
  const forwarderTimeoutCheckRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // IPC unsubscribe function
  const unsubscribeRef = useRef<(() => void) | null>(null);

  // Jitter drain timer
  const jitterDrainTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Per-peer timestamp of last P2P relay send, used to rate-limit relay during DC negotiation
  const relayLastSentRef = useRef<Map<string, number>>(new Map());

  // Off-thread audio packet decryption worker
  const decryptWorkerRef = useRef<Worker | null>(null);
  const decryptIdRef = useRef<number>(0);

  // ── Election ──────────────────────────────────────────────────────────────

  const recomputeTopology = useCallback(async (addresses: string[], existingEpoch?: number) => {
    const sorted = await computeElectionOrder(addresses, roomIdRef.current);
    const epoch = existingEpoch !== undefined ? existingEpoch : (topologyRef.current?.topologyEpoch ?? 0);
    const newTopology = buildTopology(sorted, epoch + 1);
    return { sorted, newTopology };
  }, []);

  const applyTopology = useCallback((topology: GroupTopology) => {
    if (topology.topologyEpoch < localEpochRef.current) return; // stale
    // Tie-break equal epochs: if we already have a topology at this epoch and
    // the incoming one names a DIFFERENT root, reject it.  The first topology
    // applied at each epoch is authoritative; this prevents the two-peer race
    // where both sides independently compute epoch=1 with themselves as root
    // and oscillate each other's topology on every heartbeat exchange.
    if (
      topology.topologyEpoch === localEpochRef.current &&
      topologyRef.current !== null &&
      topology.rootForwarder !== topologyRef.current.rootForwarder
    ) return;

    // A topology naming someone else as root is evidence that peer is alive;
    // reset the heartbeat ref so standby promotion doesn't misfire.
    if (topology.rootForwarder && topology.rootForwarder !== (userInfo?.address ?? '')) {
      lastRootHeartbeatRef.current = Date.now();
    }

    localEpochRef.current = topology.topologyEpoch;
    topologyRef.current = topology;

    const myAddress = userInfo?.address ?? '';
    const role = computeMyRole(myAddress, topology);
    myRoleRef.current = role;

    // Only trigger re-renders when values actually change
    setMyRole((prev) => (prev !== role ? role : prev));
    const newLabel: TopologyLabel = topology.clusters.length > 1 ? 'Hierarchical' : 'SFU';
    setTopologyLabel((prev) => (prev !== newLabel ? newLabel : prev));

    // Recompute participant roles only if any role changed
    setParticipants((prev) => {
      const newRoles = new Map(
        prev.map((p) => [p.address, computeMyRole(p.address, topology)])
      );
      const anyChange = prev.some((p) => p.role !== newRoles.get(p.address));
      if (!anyChange) return prev;
      return prev.map((p) => ({ ...p, role: newRoles.get(p.address) ?? p.role }));
    });

    // Set up forwarder heartbeat if I'm root forwarder
    if (topologyHeartbeatTimerRef.current) {
      clearInterval(topologyHeartbeatTimerRef.current);
      topologyHeartbeatTimerRef.current = null;
    }
    if (role === 'root-forwarder') {
      startTopologyHeartbeat(topology);
    }

    // Pre-connect standby backbone DataChannel — only when the root is a different
    // address than the upstream forwarder (hierarchical mode). In SFU mode both
    // point to the same root: connectUpstream below creates that one connection,
    // so calling connectStandbyChannels on the same address would immediately
    // close it via createPeerConnection.
    if (role === 'standby-forwarder') {
      const rootAddr = topology.rootForwarder;
      const assignedFwd = findAssignedForwarder(myAddress, topology);
      if (rootAddr && rootAddr !== myAddress && rootAddr !== assignedFwd) {
        const existing = peerConnectionsRef.current.get(rootAddr);
        const state = existing?.pc.connectionState;
        if (!existing || state === 'failed' || state === 'closed' || state === 'disconnected') {
          connectStandbyChannels(topology);
        }
      }
    }

    // Connect upstream DataChannel for all non-root roles.
    // standby-forwarder must also upload their own audio just like any other member.
    if (role === 'participant' || role === 'cluster-forwarder' || role === 'standby-forwarder') {
      const assignedForwarder = findAssignedForwarder(myAddress, topology);
      if (assignedForwarder && assignedForwarder !== myAddress) {
        const existing = peerConnectionsRef.current.get(assignedForwarder);
        const state = existing?.pc.connectionState;
        if (!existing || state === 'failed' || state === 'closed' || state === 'disconnected') {
          connectUpstream(assignedForwarder);
        }
      }
    }

    // Cluster-forwarder: also open a backbone upstream connection to the root
    // so it can relay frames to root (and root can fan-out back).
    if (role === 'cluster-forwarder') {
      const rootAddr = topology.rootForwarder;
      if (rootAddr && rootAddr !== myAddress) {
        const existing = peerConnectionsRef.current.get(rootAddr);
        const state = existing?.pc.connectionState;
        if (!existing || state === 'failed' || state === 'closed' || state === 'disconnected') {
          connectUpstream(rootAddr);
        }
      }
    }

    // Forwarder: set up downstream DataChannels for cluster members — only if not already connected
    if (role === 'cluster-forwarder' || role === 'root-forwarder') {
      for (const cluster of topology.clusters) {
        if (cluster.forwarder === myAddress) {
          for (const member of cluster.members) {
            if (member !== myAddress) {
              const existing = peerConnectionsRef.current.get(member);
              const state = existing?.pc.connectionState;
              if (!existing || state === 'failed' || state === 'closed' || state === 'disconnected') {
                setupDownstreamChannel(member);
              }
            }
          }
        }
      }
    }
  }, [userInfo?.address]);

  // ── Forwarder heartbeat ────────────────────────────────────────────────────

  const startTopologyHeartbeat = useCallback((topology: GroupTopology) => {
    if (!userInfo?.address) return;
    // Always clear any existing heartbeat timer before starting a new one
    // to prevent leaked intervals from accumulating.
    if (topologyHeartbeatTimerRef.current) {
      clearInterval(topologyHeartbeatTimerRef.current);
      topologyHeartbeatTimerRef.current = null;
    }
    const sendHeartbeat = async () => {
      const ts = Date.now();
      const sig = await signGroupCallFields(
        { type: 'GC_TOPOLOGY', roomId: roomIdRef.current,
          topologyEpoch: topology.topologyEpoch,
          rootForwarder: topology.rootForwarder,
          standbyForwarder: topology.standbyForwarder,
          fromAddress: userInfo.address,
          fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
      ).catch(() => '');
      if (!sig) return; // signing failed — skip this heartbeat, retry next interval
      await window.groupCall.broadcastTopology(
        roomIdRef.current,
        {
          topologyEpoch: topology.topologyEpoch,
          rootForwarder: topology.rootForwarder,
          standbyForwarder: topology.standbyForwarder,
          clusters: topology.clusters,
          lastSeen: ts,
          fromAddress: userInfo.address,
          fromPublicKey: userInfo.publicKey ?? '',
        },
        sig,
        userInfo.publicKey ?? '',
        ts
      );
    };
    sendHeartbeat();
    topologyHeartbeatTimerRef.current = setInterval(sendHeartbeat, TOPOLOGY_HEARTBEAT_MS);
  }, [userInfo]);

  // ── Standby promotion ─────────────────────────────────────────────────────

  const checkForwarderTimeout = useCallback(() => {
    const myAddress = userInfo?.address ?? '';
    if (myRoleRef.current !== 'standby-forwarder') return;
    if (Date.now() - lastRootHeartbeatRef.current < FORWARDER_TIMEOUT_MS) return;

    // Root looks dead — start cooldown before promoting
    if (promotionTimerRef.current) return; // already counting down
    promotionTimerRef.current = setTimeout(async () => {
      promotionTimerRef.current = null;
      // Check again — root might have recovered
      if (Date.now() - lastRootHeartbeatRef.current < FORWARDER_TIMEOUT_MS) return;

      const currentTopo = topologyRef.current;
      if (!currentTopo) return;

      const newEpoch = localEpochRef.current + 1;
      const addrs = [...participantsRef.current.keys()];
      const sorted = await computeElectionOrder(addrs, roomIdRef.current);
      const promotedTopo = buildTopology(sorted, newEpoch);

      // Override root with myself: the dead root may still be in participantsRef
      // (grace timer hasn't expired), so deterministic election would re-elect it.
      // Force this peer to be root/standby AND remap any cluster that still names
      // the dead root as its forwarder.
      if (currentTopo.standbyForwarder === myAddress) {
        const deadRoot = currentTopo.rootForwarder;
        const overriddenStandby = sorted.find((a) => a !== myAddress) ?? '';
        const overriddenClusters = promotedTopo.clusters.map((c) => ({
          ...c,
          forwarder: c.forwarder === deadRoot ? myAddress : c.forwarder,
          standby:   c.standby   === deadRoot ? overriddenStandby : c.standby,
        }));
        const overriddenTopo: GroupTopology = {
          ...promotedTopo,
          rootForwarder: myAddress,
          standbyForwarder: overriddenStandby,
          clusters: overriddenClusters,
        };
        applyTopology(overriddenTopo);
        // Broadcast the new topology
        const ts = Date.now();
        const sig = await signGroupCallFields(
          { type: 'GC_TOPOLOGY', roomId: roomIdRef.current, topologyEpoch: newEpoch,
            rootForwarder: overriddenTopo.rootForwarder,
            standbyForwarder: overriddenTopo.standbyForwarder,
            fromAddress: myAddress, fromPublicKey: userInfo?.publicKey ?? '', timestamp: ts }
        ).catch(() => '');
        if (!sig) return; // signing failed — abort promotion broadcast
        await window.groupCall.broadcastTopology(
          roomIdRef.current,
          {
            topologyEpoch: newEpoch,
            rootForwarder: overriddenTopo.rootForwarder,
            standbyForwarder: overriddenTopo.standbyForwarder,
            clusters: overriddenTopo.clusters,
            lastSeen: ts,
            fromAddress: myAddress,
            fromPublicKey: userInfo?.publicKey ?? '',
          },
          sig,
          userInfo?.publicKey ?? '',
          ts
        );
      }
    }, PROMOTION_COOLDOWN_MS);
  }, [applyTopology, userInfo]);

  // ── WebRTC DataChannel connections ─────────────────────────────────────────

  const STUN_SERVERS: RTCIceServer[] = [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' },
  ];

  const createPeerConnection = useCallback(
    (peerAddress: string, connId: string, role: 'upstream' | 'downstream' | 'backbone'): RTCPeerConnection => {
      const pc = new RTCPeerConnection({ iceServers: STUN_SERVERS });
      const existing = peerConnectionsRef.current.get(peerAddress);
      if (existing) {
        existing.pc.close();
      }
      peerConnectionsRef.current.set(peerAddress, { pc, dc: null, address: peerAddress, connId, role });

      pc.onicecandidate = (e) => {
        if (e.candidate && userInfo?.address) {
          window.groupCall.sendRtcSignal(
            roomIdRef.current, userInfo.address, peerAddress,
            'ice', e.candidate.toJSON(), connId
          );
        }
      };

      pc.onconnectionstatechange = () => {
        if (pc.connectionState === 'failed' || pc.connectionState === 'closed') {
          peerConnectionsRef.current.delete(peerAddress);
        }
      };

      return pc;
    },
    [userInfo?.address]
  );

  /** Connect upstream (as participant/cluster-forwarder, send to forwarder). */
  const connectUpstream = useCallback(
    async (forwarderAddress: string) => {
      if (!userInfo?.address) return;
      console.log('[GCall] connectUpstream →', forwarderAddress);
      const connId = `up-${userInfo.address}-${forwarderAddress}-${Date.now()}`;
      const pc = createPeerConnection(forwarderAddress, connId, 'upstream');
      const dc = pc.createDataChannel('audio', { ordered: false, maxRetransmits: 0 });
      dc.binaryType = 'arraybuffer';

      const pcEntry = peerConnectionsRef.current.get(forwarderAddress);
      if (pcEntry) pcEntry.dc = dc;

      dc.onopen = () => {
        console.log('[GCall] Upstream DC opened to', forwarderAddress);
        upstreamDCRef.current = dc;
        // DC is now open — clear the relay rate-limiter entry so the relay is
        // available immediately if this DC closes later.
        relayLastSentRef.current.delete(forwarderAddress);
      };

      dc.onclose = () => {
        console.log('[GCall] Upstream DC closed to', forwarderAddress);
      };

      pc.onconnectionstatechange = () => {
        console.log('[GCall] PC state (upstream →', forwarderAddress, '):', pc.connectionState);
      };

      pc.onicegatheringstatechange = () => {
        console.log('[GCall] ICE gathering (upstream →', forwarderAddress, '):', pc.iceGatheringState);
      };

      pc.oniceconnectionstatechange = () => {
        console.log('[GCall] ICE connection (upstream →', forwarderAddress, '):', pc.iceConnectionState);
      };

      // DataChannels are bidirectional: the forwarder sends audio (e.g. other
      // speakers' frames) back down through the same channel.  We must handle
      // those incoming frames here or they are silently discarded.
      dc.onmessage = (ev) => {
        handleIncomingAudioPacket(ev.data as ArrayBuffer, forwarderAddress);
      };

      const offer = await pc.createOffer();
      await pc.setLocalDescription(offer);

      const ts = Date.now();
      const sig = await signGroupCallFields(
        { type: 'GC_RTC_OFFER', roomId: roomIdRef.current, fromAddress: userInfo.address,
          toAddress: forwarderAddress, connId, fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
      ).catch(() => '');
      if (!sig) return; // signing failed — don't send unsigned RTC offer

      await window.groupCall.sendRtcSignal(
        roomIdRef.current, userInfo.address, forwarderAddress,
        'offer', offer.sdp, connId, sig, userInfo.publicKey ?? '', ts
      );
    },
    [createPeerConnection, userInfo]
  );

  /** Connect standby channels (as standby-forwarder, pre-established but idle). */
  const connectStandbyChannels = useCallback(
    async (topology: GroupTopology) => {
      if (!userInfo?.address) return;
      // Connect to root forwarder's backbone channel
      const rootAddr = topology.rootForwarder;
      if (rootAddr && rootAddr !== userInfo.address) {
        const connId = `standby-${userInfo.address}-${rootAddr}-${Date.now()}`;
        const pc = createPeerConnection(rootAddr, connId, 'backbone');
        const dc = pc.createDataChannel('standby-audio', { ordered: false, maxRetransmits: 0 });
        standbyDCRef.current = dc;

        const offer = await pc.createOffer();
        await pc.setLocalDescription(offer);

        const ts = Date.now();
        const sig = await signGroupCallFields(
          { type: 'GC_RTC_OFFER', roomId: roomIdRef.current, fromAddress: userInfo.address,
            toAddress: rootAddr, connId, fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
        ).catch(() => '');
        if (!sig) return; // signing failed — don't send unsigned RTC offer

        await window.groupCall.sendRtcSignal(
          roomIdRef.current, userInfo.address, rootAddr,
          'offer', offer.sdp, connId, sig, userInfo.publicKey ?? '', ts
        );
      }
    },
    [createPeerConnection, userInfo]
  );

  /** Forwarder: set up to accept incoming upstream connections from member. */
  const setupDownstreamChannel = useCallback(
    async (memberAddress: string) => {
      // We wait for the incoming offer via IPC event; handled in handleRtcSignal
    },
    []
  );

  /** Handle incoming RTC signal (offer/answer/ice). */
  const handleRtcSignal = useCallback(
    async (payload: any) => {
      const { type, fromAddress, connId, sdp, candidate } = payload;
      if (!userInfo?.address) return;
      console.log('[GCall] handleRtcSignal type:', type, 'from:', fromAddress);

      if (type === 'offer') {
        // Create PC to accept the offer (downstream connection from member)
        const pc = createPeerConnection(fromAddress, connId, 'downstream');

        pc.onconnectionstatechange = () => {
          console.log('[GCall] PC state (downstream ←', fromAddress, '):', pc.connectionState);
        };

        pc.oniceconnectionstatechange = () => {
          console.log('[GCall] ICE connection (downstream ←', fromAddress, '):', pc.iceConnectionState);
        };

        pc.ondatachannel = (e) => {
          const dc = e.channel;
          dc.binaryType = 'arraybuffer';
          console.log('[GCall] Downstream DC received from', fromAddress, '— channel:', dc.label);
          dc.onopen = () => {
            console.log('[GCall] Downstream DC opened from', fromAddress);
            // Clear relay rate-limiter so the relay path is immediately available
            // if this DC closes again later.
            relayLastSentRef.current.delete(fromAddress);
          };
          dc.onclose = () => console.log('[GCall] Downstream DC closed from', fromAddress);
          dc.onmessage = (ev) => {
            handleIncomingAudioPacket(ev.data as ArrayBuffer, fromAddress);
          };
          const pcEntry = peerConnectionsRef.current.get(fromAddress);
          if (pcEntry) pcEntry.dc = dc;
        };

        await pc.setRemoteDescription({ type: 'offer', sdp });
        const answer = await pc.createAnswer();
        await pc.setLocalDescription(answer);

        const ts = Date.now();
        const sig = await signGroupCallFields(
          { type: 'GC_RTC_ANSWER', roomId: roomIdRef.current, fromAddress: userInfo.address,
            toAddress: fromAddress, connId, fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
        ).catch(() => '');
        if (!sig) return; // signing failed — don't send unsigned RTC answer

        await window.groupCall.sendRtcSignal(
          roomIdRef.current, userInfo.address, fromAddress,
          'answer', answer.sdp, connId, sig, userInfo.publicKey ?? '', ts
        );
      } else if (type === 'answer') {
        const pcEntry = peerConnectionsRef.current.get(fromAddress);
        if (pcEntry) {
          await pcEntry.pc.setRemoteDescription({ type: 'answer', sdp });
        }
      } else if (type === 'ice') {
        const pcEntry = peerConnectionsRef.current.get(fromAddress);
        if (pcEntry && candidate) {
          try { await pcEntry.pc.addIceCandidate(candidate); } catch { /* ignore */ }
        }
      }
    },
    [createPeerConnection, userInfo]
  );

  // ── Audio encode ──────────────────────────────────────────────────────────

  const callEpochRef = useRef<number>(0);

  const startAudioCapture = useCallback(async () => {
    console.log('[GCall] startAudioCapture called — roomKey:', !!roomKeyRef.current, 'address:', userInfo?.address ?? '(none)');
    if (!userInfo?.address || !roomKeyRef.current) {
      console.warn('[GCall] startAudioCapture guard failed — roomKey:', !!roomKeyRef.current, 'address:', userInfo?.address ?? '(none)');
      return;
    }
    callEpochRef.current = Date.now();

    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false });
      micStreamRef.current = stream;

      const ctx = new AudioContext({ sampleRate: OPUS_SAMPLE_RATE });
      audioContextRef.current = ctx;
      const source = ctx.createMediaStreamSource(stream);

      // Set up Opus encoder (runs on main thread but is fast — just packetizes)
      const encoder = new (window as any).AudioEncoder({
        output: (chunk: any) => {
          const frame = new Uint8Array(chunk.byteLength);
          chunk.copyTo(frame);
          sendEncodedFrame(frame);
        },
        error: (e: any) => console.error('[GCall] AudioEncoder error:', e),
      });

      encoder.configure({
        codec: 'opus',
        sampleRate: OPUS_SAMPLE_RATE,
        numberOfChannels: OPUS_CHANNELS,
        bitrate: OPUS_BITRATE,
      });

      encoderRef.current = encoder;

      // Load and instantiate the capture worklet (runs on the audio worklet thread)
      console.log('[GCall] Loading capture worklet…');
      await ctx.audioWorklet.addModule('/worklets/capture-processor.js');
      console.log('[GCall] Capture worklet loaded, AudioContext state:', ctx.state);
      const captureNode = new AudioWorkletNode(ctx, 'capture-processor');
      captureWorkletRef.current = captureNode;

      // Apply current mute state to the freshly created worklet
      captureNode.port.postMessage({ type: 'mute', muted: mutedRef.current });

      // Receive complete 960-sample Opus frames + VAD flag from the worklet thread
      captureNode.port.onmessage = (e) => {
        const { frame, vad } = e.data as { frame: Float32Array; vad: boolean };
        isSpeakingRef.current = vad;
        if (!encoderRef.current) return;
        const i16 = float32ToInt16(frame);
        const audioData = new (window as any).AudioData({
          format: 's16',
          sampleRate: OPUS_SAMPLE_RATE,
          numberOfFrames: OPUS_FRAME_SAMPLES,
          numberOfChannels: OPUS_CHANNELS,
          timestamp: performance.now() * 1000,
          data: i16,
        });
        encoderRef.current.encode(audioData);
        audioData.close();
      };

      // Connect source to captureNode for worklet processing, AND connect source
      // directly to a keep-alive gain node → destination.  This puts the mic SOURCE
      // itself inside the active rendering graph so Chrome delivers real microphone
      // samples to every connected output, including captureNode's inputs.
      //
      // Why not route captureNode → gain → destination instead?
      // captureNode never writes to outputs[0][0], so its output is all-zeros.
      // Chrome's AudioParam planner sees a constant-zero output and can mark the
      // entire upstream chain as "silent", stopping sample delivery to inputs[0][0].
      //
      // Why 0.0001 instead of 0?
      // A literal gain=0 AudioParam can be detected at the planner level and treated
      // as a "silent" path even before computing signal values.  0.0001 (-80 dB) is
      // physically inaudible but prevents that parameter-level zero optimisation.
      const keepAliveGain = ctx.createGain();
      keepAliveGain.gain.value = 0.0001;
      source.connect(captureNode);
      source.connect(keepAliveGain);
      keepAliveGain.connect(ctx.destination);
      console.log('[GCall] Audio capture started — AudioContext state:', ctx.state);

    } catch (err) {
      console.error('[GCall] Audio capture failed:', err);
    }
  }, [userInfo?.address]);

  const sendEncodedFrame = useCallback((opusFrame: Uint8Array) => {
    if (!roomKeyRef.current || !userInfo?.address) return;
    if (mutedRef.current) return; // mic is muted — drop frame
    if (seqRef.current === 0) {
      console.log('[GCall] First encoded frame ready to send — role:', myRoleRef.current, 'upstreamDC:', upstreamDCRef.current?.readyState ?? 'none');
    }

    const seq = seqRef.current++ & 0xffff;
    const timestampMs = Date.now() - callEpochRef.current;
    const packet = encodePacket(
      userInfo.address, isSpeakingRef.current, seq, timestampMs,
      opusFrame, roomKeyRef.current
    );

    if (upstreamDCRef.current?.readyState === 'open') {
      // Non-root: send to assigned forwarder
      upstreamDCRef.current.send(packet.buffer as ArrayBuffer);
    } else if (myRoleRef.current === 'root-forwarder' && topologyRef.current) {
      // Root-forwarder: no upstream DC; send own audio directly to all cluster members.
      // For members whose DC is not yet open, fall back to P2P relay so audio is never
      // silently dropped during WebRTC negotiation.
      const topo = topologyRef.current;
      for (const cluster of topo.clusters) {
        if (cluster.forwarder === userInfo.address) {
          for (const member of cluster.members) {
            if (member !== userInfo.address) {
              const pcEntry = peerConnectionsRef.current.get(member);
              if (pcEntry?.dc?.readyState === 'open') {
                pcEntry.dc.send(packet.buffer as ArrayBuffer);
              } else if (roomIdRef.current) {
                // DC not open yet — relay via P2P until WebRTC establishes.
                // Rate-limit to RELAY_MIN_INTERVAL_MS per peer to avoid flooding IPC
                // at 50 Hz during the 1–5 s negotiation window.
                const now = Date.now();
                if (now - (relayLastSentRef.current.get(member) ?? 0) >= RELAY_MIN_INTERVAL_MS) {
                  relayLastSentRef.current.set(member, now);
                  // Pass raw bytes over IPC; base64 conversion happens in the main process.
                  window.groupCall.sendAudio(roomIdRef.current, member, packet).catch(() => {});
                }
              }
            }
          }
        }
      }
    } else {
      // Non-root and upstream DC not open yet — fall back to P2P relay via main process
      const topo = topologyRef.current;
      const target = topo ? findAssignedForwarder(userInfo.address, topo) : null;
      if (target && roomIdRef.current) {
        // Rate-limit to RELAY_MIN_INTERVAL_MS per peer to avoid flooding IPC
        // at 50 Hz during the 1–5 s WebRTC negotiation window.
        const now = Date.now();
        if (now - (relayLastSentRef.current.get(target) ?? 0) >= RELAY_MIN_INTERVAL_MS) {
          relayLastSentRef.current.set(target, now);
          // Pass raw bytes over IPC; base64 conversion happens in the main process.
          window.groupCall.sendAudio(roomIdRef.current, target, packet).catch(() => {});
        }
      }
    }
  }, [userInfo?.address]);

  // ── Audio decode ──────────────────────────────────────────────────────────

  const getOrCreateDecoder = useCallback((sourceAddr: string): AudioDecoder | null => {
    if (decoderMapRef.current.has(sourceAddr)) return decoderMapRef.current.get(sourceAddr)!;
    if (!audioContextRef.current) return null;
    console.log('[GCall] Creating decoder + playback worklet for', sourceAddr.slice(0, 12));

    const ctx = audioContextRef.current;

    const setupPlayback = async (): Promise<AudioWorkletNode> => {
      console.log('[GCall] Loading playback worklet for', sourceAddr.slice(0, 12));
      try {
        await ctx.audioWorklet.addModule('/worklets/playback-processor.js');
        const playNode = new AudioWorkletNode(ctx, 'playback-processor');
        playNode.connect(ctx.destination);
        playbackWorkletsRef.current.set(sourceAddr, playNode);
        console.log('[GCall] Playback worklet ready for', sourceAddr.slice(0, 12), '— ctx state:', ctx.state);
        return playNode;
      } catch (err) {
        console.error('[GCall] Playback worklet FAILED for', sourceAddr.slice(0, 12), err);
        throw err;
      }
    };

    const playNodePromise = setupPlayback();

    let pcmCount = 0;
    const decoder = new (window as any).AudioDecoder({
      output: (audioData: any) => {
        pcmCount++;
        if (pcmCount <= 3) {
          console.log('[GCall] AudioDecoder output PCM', pcmCount, 'frames:', audioData.numberOfFrames, 'for', sourceAddr.slice(0, 12));
        }
        const pcm = new Float32Array(audioData.numberOfFrames);
        audioData.copyTo(pcm, { planeIndex: 0, format: 'f32-planar' });
        audioData.close();
        const existing = playbackWorkletsRef.current.get(sourceAddr);
        if (existing) {
          existing.port.postMessage({ pcm }, [pcm.buffer]);
        } else {
          playNodePromise.then((node) => {
            node.port.postMessage({ pcm }, [pcm.buffer]);
          }).catch(() => {});
        }
      },
      error: (e: any) => console.error(`[GCall] AudioDecoder error for ${sourceAddr.slice(0, 12)}:`, e),
    });

    decoder.configure({ codec: 'opus', sampleRate: OPUS_SAMPLE_RATE, numberOfChannels: OPUS_CHANNELS });
    decoderMapRef.current.set(sourceAddr, decoder);
    return decoder;
  }, []);

  // ── Incoming audio packet processing ──────────────────────────────────────

  const handleIncomingAudioPacket = useCallback((data: ArrayBuffer, _fromAddress: string) => {
    if (!roomKeyRef.current) return;

    const buf = new Uint8Array(data);

    // Parse the plaintext header synchronously so forwarding and speaker
    // tracking can happen immediately without waiting for crypto.
    const header = parsePacketHeader(buf);
    if (!header) {
      console.warn('[GCall] parsePacketHeader returned null — malformed packet, size:', buf.byteLength);
      return;
    }

    const { sourceAddr, vad, seq } = header;
    const myAddress = userInfo?.address ?? '';

    // Log first few packets per source so we can confirm the receive path works
    const jbExisting = jitterMapRef.current.get(sourceAddr);
    if (!jbExisting) {
      console.log('[GCall] First packet from', sourceAddr.slice(0, 12), '— seq:', seq, 'vad:', vad);
    }

    // ── Active-speaker tracking ─────────────────────────────────────────────
    // Count currently-active speakers BEFORE adding sourceAddr so the gate
    // is based on the pre-existing set, not a set that was just mutated.
    const speakingCount = [...localSpeakersRef.current.entries()]
      .filter(([, t]) => Date.now() - t < 3000).length;
    const maxSpeakers = myRoleRef.current === 'root-forwarder'
      ? MAX_ACTIVE_SPEAKERS_GLOBAL
      : MAX_ACTIVE_SPEAKERS_LOCAL;
    // A frame is "active" only when VAD is set AND this source is already a
    // known speaker OR there is room for one more.
    const isActiveSpeaker = vad && (
      localSpeakersRef.current.has(sourceAddr) ||
      speakingCount < maxSpeakers
    );

    if (vad) {
      localSpeakersRef.current.set(sourceAddr, Date.now());
      lastRecvAtRef.current.set(sourceAddr, performance.now());
    }

    // If I'm a forwarder, forward to cluster members / root
    const role = myRoleRef.current;
    const topo = topologyRef.current;

    if ((role === 'cluster-forwarder' || role === 'root-forwarder') && topo) {
      // Forward active speakers only (isActiveSpeaker computed above)
      if (isActiveSpeaker) {
        if (role === 'root-forwarder') {
          // SFU mode: fan out to all members of our cluster (skipping source and self).
          // Hierarchical mode: also relay to every other cluster's forwarder.
          for (const cluster of topo.clusters) {
            if (cluster.forwarder === myAddress) {
              // Our cluster — send directly to each member
              for (const member of cluster.members) {
                if (member !== sourceAddr && member !== myAddress) {
                  const pcEntry = peerConnectionsRef.current.get(member);
                  if (pcEntry?.dc?.readyState === 'open') pcEntry.dc.send(data);
                }
              }
            } else {
              // Another cluster (hierarchical) — send to that cluster's forwarder
              const pcEntry = peerConnectionsRef.current.get(cluster.forwarder);
              if (pcEntry?.dc?.readyState === 'open') pcEntry.dc.send(data);
            }
          }
        } else {
          // Cluster forwarder: forward to root
          const rootPc = peerConnectionsRef.current.get(topo.rootForwarder);
          if (rootPc?.dc?.readyState === 'open') {
            rootPc.dc.send(data);
          }
          // Also fan out to cluster members
          for (const cluster of topo.clusters) {
            if (cluster.forwarder === myAddress) {
              for (const member of cluster.members) {
                if (member !== myAddress && member !== sourceAddr) {
                  const pcEntry = peerConnectionsRef.current.get(member);
                  if (pcEntry?.dc?.readyState === 'open') {
                    pcEntry.dc.send(data);
                  }
                }
              }
              break;
            }
          }
        }
      }
      // Fall through to local playback — the root/cluster forwarder is also a
      // participant in the call and must hear other speakers.  Forwarding and
      // local decoding are independent operations.
    }

    // Don't decrypt or play own audio.
    if (sourceAddr === myAddress) return;

    // ── Off-thread decryption ───────────────────────────────────────────────
    // Post the packet to the Worker for nacl.secretbox.open so the main thread
    // is not blocked by crypto at 50 Hz × N peers.  The Worker posts back the
    // decrypted opusFrame which is then pushed to the jitter buffer.
    if (decryptWorkerRef.current) {
      // Copy the buffer — the original `data` may still be in use by DataChannel
      // forwarding above, and ArrayBuffer transfer would detach it.
      const bufCopy = buf.slice().buffer;
      const roomKeyCopy = roomKeyRef.current.slice().buffer;
      decryptWorkerRef.current.postMessage(
        { type: 'decrypt', id: decryptIdRef.current++, buffer: bufCopy, roomKey: roomKeyCopy },
        [bufCopy, roomKeyCopy]
      );
    } else {
      // Fallback: synchronous decryption on main thread when worker is unavailable.
      const decoded = decodePacket(buf, roomKeyRef.current);
      if (!decoded) {
        console.warn('[GCall] decodePacket (sync fallback) failed — size:', buf.byteLength);
        return;
      }
      let jb = jitterMapRef.current.get(decoded.sourceAddr);
      if (!jb) {
        jb = new JitterBuffer();
        jitterMapRef.current.set(decoded.sourceAddr, jb);
      }
      jb.push(decoded.seq, decoded.opusFrame);
    }
  }, [userInfo?.address]);

  /** Start jitter drain loop. */
  const startJitterDrain = useCallback(() => {
    if (jitterDrainTimerRef.current) return;
    let tickCount = 0;
    let firstDrainLogged = false;
    jitterDrainTimerRef.current = setInterval(() => {
      for (const [addr, jb] of jitterMapRef.current) {
        const frame = jb.pop();
        if (frame) {
          if (!firstDrainLogged) {
            firstDrainLogged = true;
            console.log('[GCall] Jitter drain first pop for', addr.slice(0, 12), '— frame bytes:', frame.byteLength);
            console.log('[GCall] Decoder input frame view for', addr.slice(0, 12), {
              byteOffset: frame.byteOffset,
              byteLength: frame.byteLength,
              bufferByteLength: frame.buffer.byteLength,
            });
          }
          const decoder = getOrCreateDecoder(addr);
          if (decoder && decoder.state !== 'closed') {
            try {
              const chunk = new (window as any).EncodedAudioChunk({
                type: 'key',
                timestamp: performance.now() * 1000,
                data: frame,
              });
              decoder.decode(chunk);
            } catch (e) {
              console.warn('[GCall] decoder.decode threw:', e);
            }
          } else if (!decoder) {
            console.warn('[GCall] getOrCreateDecoder returned null for', addr.slice(0, 12));
          }
        }
      }

      // Throttle React state updates to every ~200ms (10 × 20ms ticks) so we
      // don't trigger a render on every decoded frame.
      tickCount++;
      if (tickCount % 10 === 0) {
        tickCount = 0;
        const now = Date.now();
        const speakers = [...localSpeakersRef.current.entries()]
          .filter(([, t]) => now - t < 2000)
          .map(([a]) => a)
          .slice(0, MAX_ACTIVE_SPEAKERS_GLOBAL);
        setActiveSpeakers(speakers);

        setParticipants((prev) =>
          prev.map((p) => ({
            ...p,
            speaking: speakers.includes(p.address),
          }))
        );
      }
    }, JITTER_DRAIN_INTERVAL_MS);
  }, [getOrCreateDecoder]);

  // ── Room key distribution ─────────────────────────────────────────────────

  const distributeRoomKey = useCallback(async (key: Uint8Array) => {
    if (!userInfo?.address) return;
    const myAddr = userInfo.address;
    console.log('[GCall] distributeRoomKey — recipients:', [...participantsRef.current.keys()].filter(a => a !== myAddr));

    for (const [addr, { publicKey }] of participantsRef.current) {
      if (addr === myAddr) continue;

      // Encrypt key for this participant using their Ed25519 public key.
      // Convert Ed25519 public key to Curve25519 for nacl.box, then use an
      // ephemeral keypair so the recipient can compute the same shared secret.
      try {
        const recipientPkBytes = base58DecodeRenderer(publicKey);
        const recipientCurve25519PK = ed2curve.convertPublicKey(recipientPkBytes);
        const ephemeralKP = nacl.box.keyPair();
        const sharedKey = nacl.box.before(recipientCurve25519PK, ephemeralKP.secretKey);
        const nonce = nacl.randomBytes(24);
        const ciphertext = nacl.box.after(key, nonce, sharedKey);

        // Wire format: [ephemeralPK (32)] + [nonce (24)] + [ciphertext]
        const combined = new Uint8Array(32 + 24 + ciphertext.length);
        combined.set(ephemeralKP.publicKey, 0);
        combined.set(nonce, 32);
        combined.set(ciphertext, 56);

        const b64 = uint8ToBase64(combined);
        const ts = Date.now();
      const sig = await signGroupCallFields(
        { type: 'GC_KEY', roomId: roomIdRef.current,
          toAddress: addr, fromAddress: myAddr,
          fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
      ).catch(() => '');
        if (!sig) { console.warn(`[GCall] Signing failed for GC_KEY to ${addr}`); continue; }
        await window.groupCall.sendKey(
          roomIdRef.current, addr, b64, myAddr, sig, userInfo.publicKey ?? '', ts
        );
      } catch (e) {
        console.warn(`[GCall] Failed to encrypt key for ${addr}:`, e);
      }
    }
  }, [userInfo]);

  /** Handle incoming room key. */
  const handleRoomKey = useCallback(async (payload: { encryptedKey: string }) => {
    console.log('[GCall] handleRoomKey called — encryptedKey length:', payload.encryptedKey?.length ?? 0);
    try {
      // Wire format: [ephemeralPK (32)] + [nonce (24)] + [ciphertext]
      const combined = base64ToUint8(payload.encryptedKey);
      const ephemeralPKb64  = uint8ToBase64(combined.slice(0, 32));
      const nonceb64        = uint8ToBase64(combined.slice(32, 56));
      const ciphertextb64   = uint8ToBase64(combined.slice(56));

      const result = await (window as any).sendMessage(
        'decryptBoxWithMyKey',
        { ephemeralPublicKey: ephemeralPKb64, nonce: nonceb64, ciphertext: ciphertextb64 },
        10_000
      );
      console.log('[GCall] decryptBoxWithMyKey result ok:', !!result?.decryptedKey);
      if (result?.decryptedKey) {
        roomKeyRef.current = Uint8Array.from(atob(result.decryptedKey), (c) => c.charCodeAt(0));
        console.log('[GCall] Room key set (', roomKeyRef.current.length, 'bytes), captureWorklet exists:', !!captureWorkletRef.current);
        // Non-root-forwarder: start audio now that we have the shared key
        if (!captureWorkletRef.current) {
          startAudioCapture();
        }
      }
    } catch (e) {
      console.warn('[GCall] Failed to decrypt room key:', e);
    }
  }, [startAudioCapture]);

  // ── Decrypt Worker lifecycle ──────────────────────────────────────────────

  /** Create the off-thread decrypt Worker and attach its message handler.
   *  Called at join time; the Worker is terminated in cleanup(). */
  const setupDecryptWorker = useCallback(() => {
    if (decryptWorkerRef.current) return; // already running
    const worker = new AudioDecryptWorker();
    decryptWorkerRef.current = worker;
    decryptIdRef.current = 0;

    worker.onmessage = (e: MessageEvent<{
      type: 'result';
      id: number;
      decoded: {
        sourceAddr: string;
        vad: boolean;
        seq: number;
        timestampMs: number;
        opusFrame: ArrayBuffer;
      } | null;
    }>) => {
      if (e.data.type !== 'result' || !e.data.decoded) return;
      const { sourceAddr, seq, opusFrame } = e.data.decoded;
      let jb = jitterMapRef.current.get(sourceAddr);
      if (!jb) {
        jb = new JitterBuffer();
        jitterMapRef.current.set(sourceAddr, jb);
      }
      jb.push(seq, new Uint8Array(opusFrame));
    };

    worker.onerror = (err) => {
      console.error('[GCall] AudioDecryptWorker error:', err);
    };
  }, []);

  // ── Join / Leave ──────────────────────────────────────────────────────────

  const joinGroupCall = useCallback(async (roomId: string, chatId: string) => {
    if (!userInfo?.address || !userInfo.publicKey) return;
    if (roomState !== 'idle') return;
    console.log('[GCall] joinGroupCall — roomId:', roomId, 'address:', userInfo.address);

    roomIdRef.current = roomId;
    chatIdRef.current = chatId;
    setRoomState('joining');

    // Register local address with main process
    await window.groupCall.setLocalAddresses([userInfo.address]);

    // Sign join envelope
    const ts = Date.now();
    const sig = await signGroupCallFields(
      { type: 'GC_JOIN', roomId, chatId,
        fromAddress: userInfo.address,
        fromPublicKey: userInfo.publicKey, timestamp: ts }
    ).catch(() => '');
    if (!sig) {
      console.warn('[GCall] Signing failed for GC_JOIN — aborting join');
      setRoomState('idle');
      return;
    }

    // Add self to participant list
    participantsRef.current.set(userInfo.address, { publicKey: userInfo.publicKey });
    setParticipants([{ address: userInfo.address, publicKey: userInfo.publicKey, speaking: false, role: 'participant' }]);

    // Send join to network
    await window.groupCall.join(roomId, chatId, userInfo.address, sig, userInfo.publicKey, ts);

    setRoomState('connected');

    // Reset the root-heartbeat timestamp to now so the standby-forwarder timeout
    // check doesn't misfire immediately if the hook was mounted long before joining.
    lastRootHeartbeatRef.current = Date.now();

    // Room key and audio capture are deferred until the first topology is
    // computed (in participant-joined).  Only the elected root-forwarder
    // generates and distributes the key; others wait for GC_KEY.
    setupDecryptWorker();
    startJitterDrain();
    startForwarderTimeoutCheck();
  }, [userInfo, roomState, setupDecryptWorker, startJitterDrain]);

  const leaveGroupCall = useCallback(async () => {
    if (!userInfo?.address || roomState === 'idle') return;

    // Sign leave envelope
    const ts = Date.now();
    const sig = await signGroupCallFields(
      { type: 'GC_LEAVE', roomId: roomIdRef.current,
        fromAddress: userInfo.address,
        fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
    ).catch(() => '');

    // Always clean up locally; only broadcast if signing succeeded
    if (sig) {
      await window.groupCall.leave(
        roomIdRef.current, userInfo.address, sig, userInfo.publicKey ?? '', ts
      );
    }

    cleanup();
  }, [userInfo, roomState]);

  const startForwarderTimeoutCheck = useCallback(() => {
    if (forwarderTimeoutCheckRef.current) clearInterval(forwarderTimeoutCheckRef.current);
    forwarderTimeoutCheckRef.current = setInterval(checkForwarderTimeout, 500);
  }, [checkForwarderTimeout]);

  // ── Cleanup ───────────────────────────────────────────────────────────────

  const cleanup = useCallback(() => {
    if (jitterDrainTimerRef.current) { clearInterval(jitterDrainTimerRef.current); jitterDrainTimerRef.current = null; }
    if (topologyHeartbeatTimerRef.current) { clearInterval(topologyHeartbeatTimerRef.current); topologyHeartbeatTimerRef.current = null; }
    if (promotionTimerRef.current) { clearTimeout(promotionTimerRef.current); promotionTimerRef.current = null; }
    if (forwarderTimeoutCheckRef.current) { clearInterval(forwarderTimeoutCheckRef.current); forwarderTimeoutCheckRef.current = null; }

    // Stop audio
    if (captureWorkletRef.current) {
      captureWorkletRef.current.disconnect();
      captureWorkletRef.current = null;
    }
    for (const [, node] of playbackWorkletsRef.current) {
      node.disconnect();
    }
    playbackWorkletsRef.current.clear();
    if (micStreamRef.current) {
      micStreamRef.current.getTracks().forEach((t) => t.stop());
      micStreamRef.current = null;
    }
    if (encoderRef.current && encoderRef.current.state !== 'closed') {
      encoderRef.current.close();
      encoderRef.current = null;
    }
    if (audioContextRef.current && audioContextRef.current.state !== 'closed') {
      audioContextRef.current.close();
      audioContextRef.current = null;
    }

    // Close decoders
    for (const [, dec] of decoderMapRef.current) {
      try { if (dec.state !== 'closed') dec.close(); } catch { /* ignore */ }
    }
    decoderMapRef.current.clear();
    jitterMapRef.current.clear();

    // Close peer connections
    for (const [, entry] of peerConnectionsRef.current) {
      try { entry.pc.close(); } catch { /* ignore */ }
    }
    peerConnectionsRef.current.clear();

    upstreamDCRef.current = null;
    standbyDCRef.current = null;
    relayLastSentRef.current.clear();

    // Terminate the decrypt Worker
    if (decryptWorkerRef.current) {
      decryptWorkerRef.current.terminate();
      decryptWorkerRef.current = null;
    }
    decryptIdRef.current = 0;

    // Reset state
    roomKeyRef.current = null;
    topologyRef.current = null;
    localEpochRef.current = 0;
    participantsRef.current.clear();
    seqRef.current = 0;
    localSpeakersRef.current.clear();

    setRoomState('idle');
    setParticipants([]);
    setMyRole('participant');
    setActiveSpeakers([]);

    if (unsubscribeRef.current) { unsubscribeRef.current(); unsubscribeRef.current = null; }
  }, []);

  // ── IPC event subscription ─────────────────────────────────────────────────

  useEffect(() => {
    if (!window.groupCall) return;

    const unsub = window.groupCall.onEvent((event: string, payload: any) => {
      if (event === 'gcall:participant-joined') {
        const { roomId, address, publicKey } = payload;
        if (roomId !== roomIdRef.current) return;
        if (!participantsRef.current.has(address)) {
          participantsRef.current.set(address, { publicKey });
          setParticipants((prev) => {
            if (prev.some((p) => p.address === address)) return prev;
            return [...prev, { address, publicKey, speaking: false, role: 'participant' }];
          });

          // Re-announce ourselves to the newly discovered peer so they learn about us.
          // Peers who joined the room before the newcomer already sent their GC_JOIN as a
          // flood; by the time the newcomer subscribes that flood is gone.  Re-sending a
          // fresh GC_JOIN ensures the other side fires gcall:participant-joined for us.
          if (address !== userInfo?.address && userInfo?.address && userInfo?.publicKey) {
            const rts = Date.now();
            signGroupCallFields({
              type: 'GC_JOIN', roomId, chatId: chatIdRef.current,
              fromAddress: userInfo.address,
              fromPublicKey: userInfo.publicKey, timestamp: rts,
            }).then((rsig) => {
              if (rsig) window.groupCall.join(
                roomId, chatIdRef.current, userInfo.address, rsig, userInfo.publicKey!, rts
              );
            }).catch(() => {});
          }

          // Recompute topology only when a genuinely new participant arrives.
          // Keeping this inside the guard prevents duplicate P2P relay deliveries
          // from incrementing the epoch multiple times.
          const addrs = [...participantsRef.current.keys()];
          computeElectionOrder(addrs, roomIdRef.current).then((sorted) => {
            const newTopo = buildTopology(sorted, localEpochRef.current + 1);
            applyTopology(newTopo);

            const myAddress = userInfo?.address ?? '';
            // Only the elected root-forwarder is the key authority.
            // This is deterministic: all peers agree on sorted[0].
            isInitiatorRef.current = myAddress === newTopo.rootForwarder;
            console.log('[GCall] Election result — me:', myAddress, 'rootForwarder:', newTopo.rootForwarder, 'isInitiator:', isInitiatorRef.current, 'hasKey:', !!roomKeyRef.current);

            if (isInitiatorRef.current && !roomKeyRef.current) {
              // I am the key authority — generate key, start audio, distribute
              console.log('[GCall] Generating room key and starting audio capture');
              const newKey = nacl.randomBytes(32);
              roomKeyRef.current = newKey;
              startAudioCapture();
              const origParticipants = participantsRef.current;
              participantsRef.current = new Map([[address, { publicKey }]]);
              distributeRoomKey(newKey).finally(() => {
                participantsRef.current = origParticipants;
              });
            } else if (isInitiatorRef.current && roomKeyRef.current) {
              // Already have key (subsequent participant joining) — distribute only
              console.log('[GCall] Already have key — distributing to new participant', address);
              const origParticipants = participantsRef.current;
              participantsRef.current = new Map([[address, { publicKey }]]);
              distributeRoomKey(roomKeyRef.current).finally(() => {
                participantsRef.current = origParticipants;
              });
            } else if (!isInitiatorRef.current) {
              // I am not the key authority — discard any self-generated key so
              // handleRoomKey will accept the real key from the root-forwarder
              roomKeyRef.current = null;
            }
          });
        }
      }

      if (event === 'gcall:participant-left') {
        const { roomId, address } = payload;
        if (roomId !== roomIdRef.current) return;
        participantsRef.current.delete(address);
        setParticipants((prev) => prev.filter((p) => p.address !== address));

        // Recompute topology
        const addrs = [...participantsRef.current.keys()];
        if (addrs.length > 0) {
          computeElectionOrder(addrs, roomIdRef.current).then((sorted) => {
            const newTopo = buildTopology(sorted, localEpochRef.current + 1);
            applyTopology(newTopo);
          });
        }

        // Rotate room key on leave
        if (isInitiatorRef.current && roomKeyRef.current) {
          const newKey = nacl.randomBytes(32);
          roomKeyRef.current = newKey;
          distributeRoomKey(newKey);
        }
      }

      if (event === 'gcall:topology') {
        const topo = payload as GroupTopology & { roomId: string };
        if (topo.roomId !== roomIdRef.current) return;
        lastRootHeartbeatRef.current = Date.now();
        applyTopology(topo);
      }

      if (event === 'gcall:audio') {
        const { data } = payload as { data: Uint8Array };
        // P2P relay fallback — main process already decoded base64 to binary Buffer,
        // which arrives here as a Uint8Array via structured clone. No atob needed.
        handleIncomingAudioPacket(data.buffer, '');
      }

      if (event === 'gcall:key') {
        handleRoomKey(payload);
      }

      if (event === 'gcall:rtc-signal') {
        handleRtcSignal(payload);
      }
    });

    unsubscribeRef.current = unsub;
    return () => { unsub(); unsubscribeRef.current = null; };
  }, [applyTopology, distributeRoomKey, handleIncomingAudioPacket, handleRoomKey, handleRtcSignal, startTopologyHeartbeat, userInfo?.address]);

  // Cleanup on unmount
  useEffect(() => () => { cleanup(); }, [cleanup]);

  return {
    roomState,
    participants,
    myRole,
    activeSpeakers,
    topologyLabel,
    joinGroupCall,
    leaveGroupCall,
    setMuted: (m: boolean) => {
      mutedRef.current = m;
      captureWorkletRef.current?.port.postMessage({ type: 'mute', muted: m });
    },
    roomId: roomIdRef.current,
  };
}

// ── Base58 decode helper (renderer side) ──────────────────────────────────────

function base58DecodeRenderer(str: string): Uint8Array {
  const ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
  const bytes: number[] = [];
  let num = BigInt(0);
  for (const char of str) {
    const idx = ALPHABET.indexOf(char);
    if (idx === -1) throw new Error('Invalid base58 char');
    num = num * BigInt(58) + BigInt(idx);
  }
  let hex = num.toString(16);
  if (hex.length % 2) hex = '0' + hex;
  for (let i = 0; i < hex.length; i += 2) bytes.push(parseInt(hex.slice(i, i + 2), 16));
  return new Uint8Array(bytes);
}
