/**
 * useGroupVoiceCall — decentralized group voice call hook.
 *
 * Architecture:
 *   ≤10 participants → single elected forwarder
 *   11–50 participants → hierarchical: cluster forwarders + root forwarder
 *
 * Audio pipeline:
 *   Microphone → CaptureWorkletNode (audio-worklet thread, VAD + 960-sample framing)
 *   → port.postMessage { frame, vad } → AudioEncoder (Opus ~24kbps, main thread)
 *   → packet framing (addr+seq+vad+ts+nacl.secretbox) → DataChannel to forwarder
 *   Forwarder → decrypt-reencrypt skipped; forwarder routes encrypted bytes only
 *   Receiver → DataChannel ← forwarder → jitter buffer (depth below) → drain tick from
 *   gcall-jitter-scheduler AudioWorklet (~20ms audio clock) → AudioDecoder (Opus)
 *   → PlaybackWorkletNode per speaker (audio-worklet thread, ring-buffer playback)
 *
 * Jitter: JITTER_BUFFER_SIZE frames @ 20ms each adds end-to-end latency but absorbs
 * network burstiness, decrypt-worker delay, and main-thread variance after postMessage
 * from the scheduler worklet.
 *
 * Forwarder election (deterministic, same result on all peers):
 *   Sort participants by sha256(address + roomId) → lowest = root, 2nd = standby
 *   For ≥11: partition sorted list in groups of 10, lowest-in-group = cluster forwarder
 *
 * Security:
 *   Room media key: 32-byte random key generated by initiator
 *   Distributed via window.groupCall.sendKey() using nacl.box encryption per recipient
 *   Audio frames encrypted with nacl.secretbox(opusFrame, nonce, roomKey)
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { useAtomValue } from 'jotai';
import { userInfoAtom } from '../atoms/global';
import nacl from '../encryption/nacl-fast';
import ed2curve from '../encryption/ed2curve';
import AudioDecryptWorker from '../workers/audio-decrypt.worker?worker';
import {
  GroupCallPerformanceTracker,
  collectActiveSpeakers,
  disposeParticipantAudioState,
  evaluateActiveSpeaker,
  forwardPacketForRole,
  reconcileParticipantSpeaking,
  sameAddressList,
} from '../lib/group-call/router';

const naclApi = nacl as any;

// ── Types ──────────────────────────────────────────────────────────────────────

export type RoomState = 'idle' | 'joining' | 'connected' | 'ended';
export type MyRole = 'participant' | 'cluster-forwarder' | 'root-forwarder' | 'standby-forwarder';
export type TopologyLabel = 'SFU' | 'Hierarchical';

export interface ClusterDef {
  members: string[];
  forwarder: string;
  standby: string;
}

export interface GroupTopology {
  topologyEpoch: number;
  rootForwarder: string;
  standbyForwarder: string;
  clusters: ClusterDef[];
}

export interface Participant {
  address: string;
  publicKey: string;
  speaking: boolean;
  role: MyRole;
}

// ── Constants ──────────────────────────────────────────────────────────────────

const OPUS_SAMPLE_RATE = 48000;
const OPUS_CHANNELS = 1;
const OPUS_BITRATE = 24_000;
const OPUS_FRAME_DURATION_MS = 20;
const OPUS_FRAME_SAMPLES = (OPUS_SAMPLE_RATE * OPUS_FRAME_DURATION_MS) / 1000; // 960

/** Minimum Opus frames queued before decode drain starts (20ms per frame). Playout also gates on PCM depth in worklet. */
const JITTER_BUFFER_SIZE = 6; // ~120ms — deeper buffer vs ~80ms@4; trades latency for smoothness

/** Max Opus frames decoded per remote source per jitter scheduler tick (burst catch-up). */
const JITTER_DECODE_BURST_MAX = 3;

/** Adaptive playout target (main thread → group-playout-processor). */
const ADAPTIVE_BASE_TARGET_MS = 60;
const ADAPTIVE_MIN_TARGET_MS = 80;
const ADAPTIVE_MAX_TARGET_MS = 180;
const ADAPTIVE_JITTER_K = 2.5;
const ADAPTIVE_ALPHA_UP = 0.35;
const ADAPTIVE_ALPHA_DOWN = 0.08;
const ADAPTIVE_TARGET_POST_MIN_MS = 75;
const ADAPTIVE_TARGET_MIN_DELTA_MS = 5;
const INTER_ARRIVAL_MAX_SAMPLES = 40;
const ADAPTIVE_LOSS_MS_CAP = 20;

/** After VAD goes false, keep forwarding through forwarder for this long (word gaps / breath). */
const FORWARD_VAD_HANGOVER_MS = 200;

const FORWARDER_TIMEOUT_MS = 4_500;  // miss 3 heartbeats → dead
const TOPOLOGY_HEARTBEAT_MS = 1_500; // forwarder sends GC_TOPOLOGY heartbeat
const PROMOTION_COOLDOWN_MS = 2_000; // standby waits before promoting
const FORWARDER_TIMEOUT_CHECK_MS = 1_000;

const CLUSTER_SIZE = 10;
const MAX_ACTIVE_SPEAKERS_LOCAL = 2;
const MAX_ACTIVE_SPEAKERS_GLOBAL = 3;

/** Minimum ms between P2P relay sends to the same peer while their DataChannel
 *  is still negotiating.  Caps relay IPC at ~5 frames/s instead of 50 Hz so the
 *  renderer is not flooded during the 1–5 s WebRTC negotiation window. */
const RELAY_MIN_INTERVAL_MS = 200;
const ACTIVE_SPEAKER_WINDOW_MS = 2_000;
const SPEAKER_GATE_WINDOW_MS = 3_000;
const PERF_LOG_INTERVAL_MS = 10_000;
const GCALL_DEBUG_STORAGE_KEY = 'qortal:gcall-debug';

const HEADER_LEN_OFFSET = 0;
const HEADER_ADDR_OFFSET = 1;
// After addr: [1 byte VAD][2 bytes seq][4 bytes timestamp][variable nacl.secretbox payload]

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Encode a Uint8Array to base64 without spreading into function arguments.
 *  btoa(String.fromCharCode(...bytes)) is O(n) on the call stack and causes
 *  excessive GC pressure at 50 Hz; this loop avoids the spread entirely. */
function uint8ToBase64(bytes: Uint8Array): string {
  let s = '';
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}

/** Decode a base64 string to a Uint8Array without Uint8Array.from + callback.
 *  Uint8Array.from(atob(b64), c => c.charCodeAt(0)) allocates an intermediate
 *  decoded string and iterates character-by-character via a closure; this loop
 *  reuses the pre-decoded string directly. */
function base64ToUint8(b64: string): Uint8Array {
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

function isGroupCallDebugEnabled(): boolean {
  try {
    return localStorage.getItem(GCALL_DEBUG_STORAGE_KEY) === '1';
  } catch {
    return false;
  }
}

function debugLog(...args: unknown[]): void {
  if (isGroupCallDebugEnabled()) console.log(...args);
}

function debugWarn(...args: unknown[]): void {
  if (isGroupCallDebugEnabled()) console.warn(...args);
}

/** Parse the plaintext header of an audio packet without performing crypto.
 *  Used to extract routing metadata (sourceAddr, vad, seq) for forwarding
 *  decisions before the packet is handed to the decrypt Worker.
 *  Format: [1B addrLen][addrBytes][1B vad][2B seq][4B ts][...rest] */
function parsePacketHeader(buf: Uint8Array): {
  sourceAddr: string;
  vad: boolean;
  seq: number;
  timestampMs: number;
} | null {
  try {
    let off = 0;
    const addrLen = buf[off++];
    if (addrLen === 0 || addrLen > 100) return null;
    const sourceAddr = new TextDecoder().decode(buf.slice(off, off + addrLen));
    off += addrLen;
    const vad = buf[off++] === 1;
    const seq = (buf[off++] << 8) | buf[off++];
    const timestampMs =
      (buf[off++] << 24) | (buf[off++] << 16) | (buf[off++] << 8) | buf[off++];
    return { sourceAddr, vad, seq, timestampMs };
  } catch {
    return null;
  }
}

/** sha256 → Uint8Array. Used for deterministic election. */
async function sha256Bytes(input: string): Promise<Uint8Array> {
  const enc = new TextEncoder();
  const buf = await crypto.subtle.digest('SHA-256', enc.encode(input));
  return new Uint8Array(buf);
}

/** Compare two Uint8Arrays lexicographically. */
function compareBytes(a: Uint8Array, b: Uint8Array): number {
  for (let i = 0; i < Math.min(a.length, b.length); i++) {
    if (a[i] < b[i]) return -1;
    if (a[i] > b[i]) return 1;
  }
  return a.length - b.length;
}

/** Compute election scores for all participants. Returns sorted list (lowest score first). */
async function computeElectionOrder(addresses: string[], roomId: string): Promise<string[]> {
  const scores = await Promise.all(
    addresses.map(async (addr) => ({
      addr,
      score: await sha256Bytes(addr + ':' + roomId),
    }))
  );
  scores.sort((a, b) => compareBytes(a.score, b.score));
  return scores.map((s) => s.addr);
}

/** Build topology from a sorted participant list. */
function buildTopology(
  sorted: string[],
  topologyEpoch: number
): GroupTopology {
  if (sorted.length <= CLUSTER_SIZE) {
    return {
      topologyEpoch,
      rootForwarder: sorted[0] ?? '',
      standbyForwarder: sorted[1] ?? '',
      clusters: [
        {
          members: sorted,
          forwarder: sorted[0] ?? '',
          standby: sorted[1] ?? '',
        },
      ],
    };
  }

  // Hierarchical: cluster forwarders + root
  const clusters: ClusterDef[] = [];
  for (let i = 0; i < sorted.length; i += CLUSTER_SIZE) {
    const chunk = sorted.slice(i, i + CLUSTER_SIZE);
    clusters.push({
      members: chunk,
      forwarder: chunk[0],
      standby: chunk[1] ?? chunk[0],
    });
  }

  // Root forwarder is the cluster forwarder with the lowest overall score
  const clusterForwarders = clusters.map((c) => c.forwarder);
  const rootForwarder = clusterForwarders[0];
  const standbyForwarder = clusterForwarders[1] ?? clusterForwarders[0];

  return { topologyEpoch, rootForwarder, standbyForwarder, clusters };
}

/** Compare-only fingerprint: normalize cluster/member order so duplicate applies short-circuit safely. */
function topologyStructureFingerprint(topology: GroupTopology): string {
  const normClusters = topology.clusters
    .map((c) => ({
      forwarder: c.forwarder,
      standby: c.standby,
      members: [...c.members].sort(),
    }))
    .sort((a, b) => a.forwarder.localeCompare(b.forwarder));
  return JSON.stringify({
    topologyEpoch: topology.topologyEpoch,
    rootForwarder: topology.rootForwarder,
    standbyForwarder: topology.standbyForwarder,
    clusters: normClusters,
  });
}

/** Determine this node's role given a topology. */
function computeMyRole(myAddress: string, topology: GroupTopology): MyRole {
  if (myAddress === topology.rootForwarder) return 'root-forwarder';
  if (myAddress === topology.standbyForwarder) return 'standby-forwarder';
  for (const cluster of topology.clusters) {
    if (myAddress === cluster.forwarder) return 'cluster-forwarder';
  }
  return 'participant';
}

/** Find which cluster forwarder a participant should send to. */
function findAssignedForwarder(myAddress: string, topology: GroupTopology): string {
  for (const cluster of topology.clusters) {
    if (cluster.members.includes(myAddress)) {
      return cluster.forwarder;
    }
  }
  return topology.rootForwarder;
}

/** Encode packet header + nacl.secretbox payload.
 *  Format: [1B addrLen][addrBytes][1B vad][2B seq][4B ts][24B nonce][ciphertext]
 */
function encodePacket(
  sourceAddr: string,
  vad: boolean,
  seq: number,
  timestampMs: number,
  opusFrame: Uint8Array,
  roomKey: Uint8Array
): Uint8Array {
  const addrBytes = new TextEncoder().encode(sourceAddr);
  const addrLen = addrBytes.length;

  const nonce = naclApi.randomBytes(24);
  const ciphertext = naclApi.secretbox(opusFrame, nonce, roomKey);

  const total = 1 + addrLen + 1 + 2 + 4 + 24 + ciphertext.length;
  const buf = new Uint8Array(total);
  let off = 0;

  buf[off++] = addrLen;
  buf.set(addrBytes, off); off += addrLen;
  buf[off++] = vad ? 1 : 0;
  buf[off++] = (seq >> 8) & 0xff;
  buf[off++] = seq & 0xff;
  buf[off++] = (timestampMs >>> 24) & 0xff;
  buf[off++] = (timestampMs >>> 16) & 0xff;
  buf[off++] = (timestampMs >>> 8) & 0xff;
  buf[off++] = timestampMs & 0xff;
  buf.set(nonce, off); off += 24;
  buf.set(ciphertext, off);

  return buf;
}

/** Decode packet. Returns null if decryption fails. */
function decodePacket(
  buf: Uint8Array,
  roomKey: Uint8Array
): { sourceAddr: string; vad: boolean; seq: number; timestampMs: number; opusFrame: Uint8Array } | null {
  try {
    let off = 0;
    const addrLen = buf[off++];
    const sourceAddr = new TextDecoder().decode(buf.slice(off, off + addrLen)); off += addrLen;
    const vad = buf[off++] === 1;
    const seq = (buf[off++] << 8) | buf[off++];
    const timestampMs = (buf[off++] << 24) | (buf[off++] << 16) | (buf[off++] << 8) | buf[off++];
    const nonce = buf.slice(off, off + 24); off += 24;
    const ciphertext = buf.slice(off);
    const plaintext = naclApi.secretbox.open(ciphertext, nonce, roomKey);
    if (!plaintext) return null;
    return { sourceAddr, vad, seq, timestampMs, opusFrame: plaintext };
  } catch {
    return null;
  }
}

/** Convert Float32 PCM to Int16 PCM for WebCodecs AudioData. */
function float32ToInt16(f32: Float32Array): Int16Array {
  const i16 = new Int16Array(f32.length);
  for (let i = 0; i < f32.length; i++) {
    i16[i] = Math.max(-32768, Math.min(32767, Math.round(f32[i] * 32767)));
  }
  return i16;
}

/**
 * Sign fields for group call messages.
 * Delegates to the background process (which holds the private key) via
 * the same 'signPresenceMessage' IPC used by useP2PChat and presence.
 * The background performs: sort keys → JSON.stringify → Ed25519 → Base58.
 */
async function signGroupCallFields(
  fields: Record<string, unknown>
): Promise<string> {
  const result = await (window as any).sendMessage('signPresenceMessage', fields, 10_000);
  if (result?.error) throw new Error(String(result.error));
  if (typeof result?.signature !== 'string') throw new Error('signPresenceMessage returned no signature');
  return result.signature as string;
}

// ── Jitter buffer ──────────────────────────────────────────────────────────────

interface JitterEntry {
  seq: number;
  opusFrame: Uint8Array;
  receivedAt: number;
}

class JitterBuffer {
  private entries: JitterEntry[] = [];
  private lastPlayedSeq = -1;
  private pendingMissedSeq = 0;

  /** Pop-side gap detection: call after pop; returns missed frame count since last pop. */
  consumePendingMissedFrames(): number {
    const m = this.pendingMissedSeq;
    this.pendingMissedSeq = 0;
    return m;
  }

  push(seq: number, opusFrame: Uint8Array): void {
    if (seq <= this.lastPlayedSeq) return; // already played or older
    let insertAt = this.entries.length;
    while (insertAt > 0) {
      const prev = this.entries[insertAt - 1];
      if (prev.seq === seq) return; // duplicate
      if (prev.seq < seq) break;
      insertAt--;
    }
    this.entries.splice(insertAt, 0, { seq, opusFrame, receivedAt: performance.now() });
    const maxEntries = JITTER_BUFFER_SIZE * 2;
    if (this.entries.length > maxEntries) {
      this.entries.splice(0, this.entries.length - maxEntries);
    }
  }

  /** Returns next frame to play, or null if buffer not ready. */
  pop(): Uint8Array | null {
    if (this.entries.length < JITTER_BUFFER_SIZE) return null;
    const entry = this.entries.shift();
    if (!entry) return null;
    if (this.lastPlayedSeq >= 0) {
      const expected = (this.lastPlayedSeq + 1) & 0xffff;
      const gap = (entry.seq - expected + 65536) % 65536;
      if (gap > 0 && gap <= 48) this.pendingMissedSeq += gap;
    }
    this.lastPlayedSeq = entry.seq;
    return entry.opusFrame;
  }

  hasReadyFrame(): boolean {
    return this.entries.length >= JITTER_BUFFER_SIZE;
  }

  clear(): void {
    this.entries = [];
    this.lastPlayedSeq = -1;
    this.pendingMissedSeq = 0;
  }
}

// ── DataChannel manager ────────────────────────────────────────────────────────

interface PeerConnection {
  pc: RTCPeerConnection;
  dc: RTCDataChannel | null;
  address: string;
  connId: string;
  role: 'upstream' | 'downstream' | 'backbone';
}

// ── Main hook ──────────────────────────────────────────────────────────────────

export function useGroupVoiceCall(uiActive = false) {
  const userInfo = useAtomValue(userInfoAtom);

  // ── Room state ──────────────────────────────────────────────────────────────

  const [roomState, setRoomState] = useState<RoomState>('idle');
  /** Mirrors roomState for callbacks that must not depend on roomState (avoids spurious cleanup). */
  const roomStateRef = useRef<RoomState>(roomState);
  roomStateRef.current = roomState;

  const [participants, setParticipants] = useState<Participant[]>([]);
  const [myRole, setMyRole] = useState<MyRole>('participant');
  const [activeSpeakers, setActiveSpeakers] = useState<string[]>([]);
  const [topologyLabel, setTopologyLabel] = useState<TopologyLabel>('SFU');
  const [metrics, setMetrics] = useState(() => new GroupCallPerformanceTracker().getSnapshot());

  // ── Refs ────────────────────────────────────────────────────────────────────

  const roomIdRef = useRef<string>('');
  const chatIdRef = useRef<string>('');

  // Room key (32-byte symmetric key)
  const roomKeyRef = useRef<Uint8Array | null>(null);
  // Was I the one who generated the key? (initiator)
  const isInitiatorRef = useRef(false);

  // Topology state
  const topologyRef = useRef<GroupTopology | null>(null);
  const localEpochRef = useRef<number>(0);
  const myRoleRef = useRef<MyRole>('participant');
  /** lastJoinTs / joinGeneration = latest seen GC_JOIN for this address (rejoin detection). */
  const participantsRef = useRef<
    Map<string, { publicKey: string; lastJoinTs: number; joinGeneration?: number }>
  >(new Map());
  /** Stable per logical call session; same value on mesh re-announces until cleanup. */
  const joinGenerationRef = useRef<number | null>(null);

  // Audio
  const audioContextRef = useRef<AudioContext | null>(null);
  const micStreamRef = useRef<MediaStream | null>(null);
  const captureWorkletRef = useRef<AudioWorkletNode | null>(null);
  const playbackWorkletsRef = useRef<Map<string, AudioWorkletNode>>(new Map());
  const playbackWorkletModulePromiseRef = useRef<Promise<void> | null>(null);
  const encoderRef = useRef<AudioEncoder | null>(null);

  // VAD speaking flag — set from the capture worklet's port message
  const isSpeakingRef = useRef(false);
  // Mute: when true, both sendEncodedFrame and the capture worklet gate output
  const mutedRef = useRef(false);

  // Per-source decoders and jitter buffers
  const decoderMapRef = useRef<Map<string, AudioDecoder>>(new Map());
  const jitterMapRef = useRef<Map<string, JitterBuffer>>(new Map());
  const lastRecvAtRef = useRef<Map<string, number>>(new Map());

  // Outgoing seq counter per source
  const seqRef = useRef<number>(0);

  // Speaker tracking (for VAD-based active speaker selection)
  const localSpeakersRef = useRef<Map<string, number>>(new Map()); // addr → lastVadTime
  /** Last wall time we saw vad true per source (for forwarder hangover after speech). */
  const lastVadTrueAtRef = useRef<Map<string, number>>(new Map());

  // WebRTC peer connections
  const peerConnectionsRef = useRef<Map<string, PeerConnection>>(new Map());

  // Upstream DC to assigned forwarder
  const upstreamDCRef = useRef<RTCDataChannel | null>(null);
  // Standby DC (pre-connected)
  const standbyDCRef = useRef<RTCDataChannel | null>(null);

  // Forwarder heartbeat timer (for sending topology heartbeats)
  const topologyHeartbeatTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  // Standby promotion timer
  const promotionTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Last time we saw a topology heartbeat from root
  const lastRootHeartbeatRef = useRef<number>(Date.now());
  // Forwarder-timeout polling interval (runs every 500ms)
  const forwarderTimeoutCheckRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const uiActiveRef = useRef(uiActive);

  // IPC unsubscribe function
  const unsubscribeRef = useRef<(() => void) | null>(null);

  /** Drives jitter-buffer drain on the audio render clock (see gcall-jitter-scheduler worklet). */
  const jitterSchedulerNodeRef = useRef<AudioWorkletNode | null>(null);
  const runJitterDrainTickRef = useRef<() => void>(() => {});
  const jitterDrainReactTickCountRef = useRef(0);
  const jitterFirstDrainLoggedRef = useRef(false);
  const activeJitterSourcesRef = useRef<Set<string>>(new Set());
  /** Bumps before each async topology election (join or leave); stale continuations no-op after await. */
  const topologyAsyncGenRef = useRef(0);

  /** Inter-arrival times (ms) for adaptive target; last wall packet arrival for delta. */
  const lastPacketArrivalAtRef = useRef<Map<string, number>>(new Map());
  const interArrivalSamplesRef = useRef<Map<string, number[]>>(new Map());
  const smoothedPlayoutTargetRef = useRef<Map<string, number>>(new Map());
  const lastSentPlayoutTargetRef = useRef<Map<string, number>>(new Map());
  const lastPlayoutTargetPostAtRef = useRef<Map<string, number>>(new Map());
  /** Seq-gap count accumulated during last drain tick per source (feeds loss term). */
  const lastDrainMissedRef = useRef<Map<string, number>>(new Map());

  // Per-peer timestamp of last P2P relay send, used to rate-limit relay during DC negotiation
  const relayLastSentRef = useRef<Map<string, number>>(new Map());

  // Off-thread audio packet decryption worker
  const decryptWorkerRef = useRef<Worker | null>(null);
  const decryptIdRef = useRef<number>(0);
  const encryptIdRef = useRef<number>(0);
  const metricsRef = useRef(new GroupCallPerformanceTracker());
  const metricsFlushTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── Election ──────────────────────────────────────────────────────────────

  const getConnIdTimestamp = useCallback((connId: string): number | null => {
    const lastDash = connId.lastIndexOf('-');
    if (lastDash === -1) return null;
    const ts = Number(connId.slice(lastDash + 1));
    return Number.isFinite(ts) ? ts : null;
  }, []);

  const isPeerConnectionInactive = useCallback((entry?: PeerConnection) => {
    const state = entry?.pc.connectionState;
    return !entry || state === 'failed' || state === 'closed' || state === 'disconnected';
  }, []);

  const closePeerConnection = useCallback((peerAddress: string, expectedConnId?: string) => {
    const entry = peerConnectionsRef.current.get(peerAddress);
    if (!entry) return;
    if (expectedConnId && entry.connId !== expectedConnId) return;

    peerConnectionsRef.current.delete(peerAddress);
    relayLastSentRef.current.delete(peerAddress);

    if (entry.dc) {
      if (upstreamDCRef.current === entry.dc) upstreamDCRef.current = null;
      if (standbyDCRef.current === entry.dc) standbyDCRef.current = null;
      try { entry.dc.close(); } catch { /* ignore */ }
    }

    try { entry.pc.close(); } catch { /* ignore */ }
  }, []);

  const updateMetricResourceCounts = useCallback(() => {
    metricsRef.current.setResourceCounts({
      decoders: decoderMapRef.current.size,
      playbackNodes: playbackWorkletsRef.current.size,
      jitterBuffers: jitterMapRef.current.size,
    });
  }, []);

  const recordInterArrivalForPlayout = useCallback((sourceAddr: string) => {
    const now = performance.now();
    const last = lastPacketArrivalAtRef.current.get(sourceAddr);
    lastPacketArrivalAtRef.current.set(sourceAddr, now);
    if (last === undefined) return;
    const delta = now - last;
    if (delta <= 0 || delta > 2000) return;
    let arr = interArrivalSamplesRef.current.get(sourceAddr);
    if (!arr) {
      arr = [];
      interArrivalSamplesRef.current.set(sourceAddr, arr);
    }
    arr.push(delta);
    while (arr.length > INTER_ARRIVAL_MAX_SAMPLES) arr.shift();
  }, []);

  const tickAdaptivePlayoutTargets = useCallback(() => {
    const now = performance.now();
    for (const addr of activeJitterSourcesRef.current) {
      const node = playbackWorkletsRef.current.get(addr);
      if (!node) continue;

      const samples = interArrivalSamplesRef.current.get(addr);
      let jitterMs = 0;
      if (samples && samples.length >= 3) {
        const mean = samples.reduce((a, b) => a + b, 0) / samples.length;
        let varSum = 0;
        for (const d of samples) varSum += (d - mean) * (d - mean);
        jitterMs = Math.sqrt(Math.max(0, varSum / samples.length));
      }

      const missed = lastDrainMissedRef.current.get(addr) ?? 0;
      lastDrainMissedRef.current.set(addr, 0);
      const lossPenalty = Math.min(ADAPTIVE_LOSS_MS_CAP, missed * 2);

      let ideal =
        ADAPTIVE_BASE_TARGET_MS + ADAPTIVE_JITTER_K * jitterMs + lossPenalty;
      ideal = Math.max(ADAPTIVE_MIN_TARGET_MS, Math.min(ADAPTIVE_MAX_TARGET_MS, ideal));

      let smooth = smoothedPlayoutTargetRef.current.get(addr);
      if (smooth === undefined) smooth = ideal;
      if (ideal > smooth) {
        smooth += ADAPTIVE_ALPHA_UP * (ideal - smooth);
      } else {
        smooth += ADAPTIVE_ALPHA_DOWN * (ideal - smooth);
      }
      smoothedPlayoutTargetRef.current.set(addr, smooth);

      const lastSent = lastSentPlayoutTargetRef.current.get(addr);
      const lastPost = lastPlayoutTargetPostAtRef.current.get(addr) ?? 0;
      if (lastSent !== undefined && Math.abs(smooth - lastSent) <= ADAPTIVE_TARGET_MIN_DELTA_MS) {
        continue;
      }
      if (lastSent !== undefined && now - lastPost < ADAPTIVE_TARGET_POST_MIN_MS) {
        continue;
      }

      node.port.postMessage({ type: 'target', targetPlayoutMs: smooth });
      lastSentPlayoutTargetRef.current.set(addr, smooth);
      lastPlayoutTargetPostAtRef.current.set(addr, now);
    }
  }, []);

  const flushMetrics = useCallback(() => {
    updateMetricResourceCounts();
    const snapshot = metricsRef.current.getSnapshot();
    if (uiActiveRef.current || roomStateRef.current !== 'idle') {
      setMetrics((prev) => {
        const unchanged =
          prev.role === snapshot.role &&
          prev.packetsReceived === snapshot.packetsReceived &&
          prev.packetsForwarded === snapshot.packetsForwarded &&
          prev.packetsDecoded === snapshot.packetsDecoded &&
          prev.packetsDropped === snapshot.packetsDropped &&
          prev.relayPacketsSent === snapshot.relayPacketsSent &&
          prev.relayPacketsReceived === snapshot.relayPacketsReceived &&
          prev.jitterUnderruns === snapshot.jitterUnderruns &&
          prev.missingFrames === snapshot.missingFrames &&
          prev.concealmentTicks === snapshot.concealmentTicks &&
          prev.decoderCount === snapshot.decoderCount &&
          prev.playbackNodeCount === snapshot.playbackNodeCount &&
          prev.jitterBufferCount === snapshot.jitterBufferCount &&
          prev.avgIncomingPacketMs === snapshot.avgIncomingPacketMs &&
          prev.maxIncomingPacketMs === snapshot.maxIncomingPacketMs &&
          prev.avgJitterTickMs === snapshot.avgJitterTickMs &&
          prev.maxJitterTickMs === snapshot.maxJitterTickMs &&
          prev.avgPcmBufferedMs === snapshot.avgPcmBufferedMs &&
          prev.playoutOutsideTargetFraction === snapshot.playoutOutsideTargetFraction &&
          prev.lastUpdatedAt === snapshot.lastUpdatedAt;
        return unchanged ? prev : snapshot;
      });
    }
    if (isGroupCallDebugEnabled()) {
      debugLog('[GCall] metrics', snapshot);
    }
  }, [updateMetricResourceCounts]);

  const startMetricsFlushLoop = useCallback(() => {
    if (metricsFlushTimerRef.current) return;
    metricsFlushTimerRef.current = setInterval(flushMetrics, PERF_LOG_INTERVAL_MS);
  }, [flushMetrics]);

  const stopMetricsFlushLoop = useCallback(() => {
    if (!metricsFlushTimerRef.current) return;
    clearInterval(metricsFlushTimerRef.current);
    metricsFlushTimerRef.current = null;
  }, []);

  useEffect(() => {
    uiActiveRef.current = uiActive;
    if (uiActive) {
      flushMetrics();
    }
  }, [flushMetrics, uiActive]);

  const syncDecryptWorkerRoomKey = useCallback((roomKey: Uint8Array | null) => {
    if (!decryptWorkerRef.current) return;
    if (!roomKey) {
      decryptWorkerRef.current.postMessage({ type: 'clearRoomKey' });
      return;
    }
    const roomKeyCopy = roomKey.slice().buffer;
    decryptWorkerRef.current.postMessage({ type: 'setRoomKey', roomKey: roomKeyCopy }, [roomKeyCopy]);
  }, []);

  const disposeParticipantAudio = useCallback((address: string) => {
    disposeParticipantAudioState(
      address,
      decoderMapRef.current,
      playbackWorkletsRef.current,
      jitterMapRef.current as Map<string, { clear?: () => void }>,
      lastRecvAtRef.current,
      localSpeakersRef.current
    );
    lastVadTrueAtRef.current.delete(address);
    lastPacketArrivalAtRef.current.delete(address);
    interArrivalSamplesRef.current.delete(address);
    smoothedPlayoutTargetRef.current.delete(address);
    lastSentPlayoutTargetRef.current.delete(address);
    lastPlayoutTargetPostAtRef.current.delete(address);
    lastDrainMissedRef.current.delete(address);
    updateMetricResourceCounts();
  }, [updateMetricResourceCounts]);

  const sendPacketToPeer = useCallback((address: string, data: ArrayBuffer): boolean => {
    const pcEntry = peerConnectionsRef.current.get(address);
    if (pcEntry?.dc?.readyState !== 'open') return false;
    pcEntry.dc.send(data);
    return true;
  }, []);

  const applyTopology = useCallback((topology: GroupTopology) => {
    if (topology.topologyEpoch < localEpochRef.current) return; // stale
    // Tie-break equal epochs: if we already have a topology at this epoch and
    // the incoming one names a DIFFERENT root, reject it.  The first topology
    // applied at each epoch is authoritative; this prevents the two-peer race
    // where both sides independently compute epoch=1 with themselves as root
    // and oscillate each other's topology on every heartbeat exchange.
    if (
      topology.topologyEpoch === localEpochRef.current &&
      topologyRef.current !== null &&
      topology.rootForwarder !== topologyRef.current.rootForwarder
    ) return;

    const prevTopo = topologyRef.current;
    if (
      prevTopo &&
      topology.topologyEpoch === localEpochRef.current &&
      topologyStructureFingerprint(topology) === topologyStructureFingerprint(prevTopo)
    ) {
      return;
    }

    // A topology naming someone else as root is evidence that peer is alive;
    // reset the heartbeat ref so standby promotion doesn't misfire.
    if (topology.rootForwarder && topology.rootForwarder !== (userInfo?.address ?? '')) {
      lastRootHeartbeatRef.current = Date.now();
    }

    localEpochRef.current = topology.topologyEpoch;
    topologyRef.current = topology;

    const myAddress = userInfo?.address ?? '';
    const role = computeMyRole(myAddress, topology);
    myRoleRef.current = role;
    metricsRef.current.setRole(role);

    // Only trigger re-renders when values actually change
    setMyRole((prev) => (prev !== role ? role : prev));
    const newLabel: TopologyLabel = topology.clusters.length > 1 ? 'Hierarchical' : 'SFU';
    setTopologyLabel((prev) => (prev !== newLabel ? newLabel : prev));

    // Recompute participant roles only if any role changed
    setParticipants((prev) => {
      const newRoles = new Map(
        prev.map((p) => [p.address, computeMyRole(p.address, topology)])
      );
      const anyChange = prev.some((p) => p.role !== newRoles.get(p.address));
      if (!anyChange) return prev;
      return prev.map((p) => ({ ...p, role: newRoles.get(p.address) ?? p.role }));
    });

    // Set up forwarder heartbeat if I'm root forwarder
    if (topologyHeartbeatTimerRef.current) {
      clearInterval(topologyHeartbeatTimerRef.current);
      topologyHeartbeatTimerRef.current = null;
    }
    if (role === 'root-forwarder') {
      startTopologyHeartbeat(topology);
    }

    // Pre-connect standby backbone DataChannel — only when the root is a different
    // address than the upstream forwarder (hierarchical mode). In SFU mode both
    // point to the same root: connectUpstream below creates that one connection,
    // so calling connectStandbyChannels on the same address would immediately
    // close it via createPeerConnection.
    if (role === 'standby-forwarder') {
      const rootAddr = topology.rootForwarder;
      const assignedFwd = findAssignedForwarder(myAddress, topology);
      if (rootAddr && rootAddr !== myAddress && rootAddr !== assignedFwd) {
        const existing = peerConnectionsRef.current.get(rootAddr);
        if (isPeerConnectionInactive(existing)) {
          connectStandbyChannels(topology);
        }
      }
    }

    // Connect upstream DataChannel for all non-root roles.
    // standby-forwarder must also upload their own audio just like any other member.
    if (role === 'participant' || role === 'cluster-forwarder' || role === 'standby-forwarder') {
      const assignedForwarder = findAssignedForwarder(myAddress, topology);
      if (assignedForwarder && assignedForwarder !== myAddress) {
        const existing = peerConnectionsRef.current.get(assignedForwarder);
        if (isPeerConnectionInactive(existing)) {
          connectUpstream(assignedForwarder);
        }
      }
    }

    // Cluster-forwarder: also open a backbone upstream connection to the root
    // so it can relay frames to root (and root can fan-out back).
    if (role === 'cluster-forwarder') {
      const rootAddr = topology.rootForwarder;
      if (rootAddr && rootAddr !== myAddress) {
        const existing = peerConnectionsRef.current.get(rootAddr);
        if (isPeerConnectionInactive(existing)) {
          connectUpstream(rootAddr);
        }
      }
    }

    // Forwarder: set up downstream DataChannels for cluster members — only if not already connected
    if (role === 'cluster-forwarder' || role === 'root-forwarder') {
      for (const cluster of topology.clusters) {
        if (cluster.forwarder === myAddress) {
          for (const member of cluster.members) {
            if (member !== myAddress) {
              const existing = peerConnectionsRef.current.get(member);
              if (isPeerConnectionInactive(existing)) {
                setupDownstreamChannel(member);
              }
            }
          }
        }
      }
    }
  }, [userInfo?.address]);

  // ── Forwarder heartbeat ────────────────────────────────────────────────────

  const startTopologyHeartbeat = useCallback((topology: GroupTopology) => {
    if (!userInfo?.address) return;
    // Always clear any existing heartbeat timer before starting a new one
    // to prevent leaked intervals from accumulating.
    if (topologyHeartbeatTimerRef.current) {
      clearInterval(topologyHeartbeatTimerRef.current);
      topologyHeartbeatTimerRef.current = null;
    }
    const sendHeartbeat = async () => {
      const ts = Date.now();
      const sig = await signGroupCallFields(
        { type: 'GC_TOPOLOGY', roomId: roomIdRef.current,
          topologyEpoch: topology.topologyEpoch,
          rootForwarder: topology.rootForwarder,
          standbyForwarder: topology.standbyForwarder,
          fromAddress: userInfo.address,
          fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
      ).catch(() => '');
      if (!sig) return; // signing failed — skip this heartbeat, retry next interval
      await window.groupCall.broadcastTopology(
        roomIdRef.current,
        {
          topologyEpoch: topology.topologyEpoch,
          rootForwarder: topology.rootForwarder,
          standbyForwarder: topology.standbyForwarder,
          clusters: topology.clusters,
          lastSeen: ts,
          fromAddress: userInfo.address,
          fromPublicKey: userInfo.publicKey ?? '',
        },
        sig,
        userInfo.publicKey ?? '',
        ts
      );
    };
    sendHeartbeat();
    topologyHeartbeatTimerRef.current = setInterval(sendHeartbeat, TOPOLOGY_HEARTBEAT_MS);
  }, [userInfo]);

  // ── Standby promotion ─────────────────────────────────────────────────────

  const checkForwarderTimeout = useCallback(() => {
    const myAddress = userInfo?.address ?? '';
    if (myRoleRef.current !== 'standby-forwarder') return;
    if (Date.now() - lastRootHeartbeatRef.current < FORWARDER_TIMEOUT_MS) return;

    // Root looks dead — start cooldown before promoting
    if (promotionTimerRef.current) return; // already counting down
    promotionTimerRef.current = setTimeout(async () => {
      promotionTimerRef.current = null;
      // Check again — root might have recovered
      if (Date.now() - lastRootHeartbeatRef.current < FORWARDER_TIMEOUT_MS) return;

      const currentTopo = topologyRef.current;
      if (!currentTopo) return;

      const newEpoch = localEpochRef.current + 1;
      const addrs = [...participantsRef.current.keys()];
      const sorted = await computeElectionOrder(addrs, roomIdRef.current);
      const promotedTopo = buildTopology(sorted, newEpoch);

      // Override root with myself: the dead root may still be in participantsRef
      // (grace timer hasn't expired), so deterministic election would re-elect it.
      // Force this peer to be root/standby AND remap any cluster that still names
      // the dead root as its forwarder.
      if (currentTopo.standbyForwarder === myAddress) {
        const deadRoot = currentTopo.rootForwarder;
        const overriddenStandby = sorted.find((a) => a !== myAddress) ?? '';
        const overriddenClusters = promotedTopo.clusters.map((c) => ({
          ...c,
          forwarder: c.forwarder === deadRoot ? myAddress : c.forwarder,
          standby:   c.standby   === deadRoot ? overriddenStandby : c.standby,
        }));
        const overriddenTopo: GroupTopology = {
          ...promotedTopo,
          rootForwarder: myAddress,
          standbyForwarder: overriddenStandby,
          clusters: overriddenClusters,
        };
        applyTopology(overriddenTopo);
        // Broadcast the new topology
        const ts = Date.now();
        const sig = await signGroupCallFields(
          { type: 'GC_TOPOLOGY', roomId: roomIdRef.current, topologyEpoch: newEpoch,
            rootForwarder: overriddenTopo.rootForwarder,
            standbyForwarder: overriddenTopo.standbyForwarder,
            fromAddress: myAddress, fromPublicKey: userInfo?.publicKey ?? '', timestamp: ts }
        ).catch(() => '');
        if (!sig) return; // signing failed — abort promotion broadcast
        await window.groupCall.broadcastTopology(
          roomIdRef.current,
          {
            topologyEpoch: newEpoch,
            rootForwarder: overriddenTopo.rootForwarder,
            standbyForwarder: overriddenTopo.standbyForwarder,
            clusters: overriddenTopo.clusters,
            lastSeen: ts,
            fromAddress: myAddress,
            fromPublicKey: userInfo?.publicKey ?? '',
          },
          sig,
          userInfo?.publicKey ?? '',
          ts
        );
      }
    }, PROMOTION_COOLDOWN_MS);
  }, [applyTopology, userInfo]);

  // ── WebRTC DataChannel connections ─────────────────────────────────────────

  const STUN_SERVERS: RTCIceServer[] = [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' },
  ];

  const createPeerConnection = useCallback(
    (peerAddress: string, connId: string, role: 'upstream' | 'downstream' | 'backbone'): RTCPeerConnection => {
      const pc = new RTCPeerConnection({ iceServers: STUN_SERVERS });
      closePeerConnection(peerAddress);
      peerConnectionsRef.current.set(peerAddress, { pc, dc: null, address: peerAddress, connId, role });

      pc.onicecandidate = (e) => {
        if (e.candidate && userInfo?.address) {
          window.groupCall.sendRtcSignal(
            roomIdRef.current, userInfo.address, peerAddress,
            'ice', e.candidate.toJSON(), connId
          );
        }
      };

      pc.addEventListener('connectionstatechange', () => {
        if (pc.connectionState === 'failed' || pc.connectionState === 'closed' || pc.connectionState === 'disconnected') {
          closePeerConnection(peerAddress, connId);
        }
      });

      return pc;
    },
    [closePeerConnection, userInfo?.address]
  );

  /** Connect upstream (as participant/cluster-forwarder, send to forwarder). */
  const connectUpstream = useCallback(
    async (forwarderAddress: string) => {
      if (!userInfo?.address) return;
      debugLog('[GCall] connectUpstream →', forwarderAddress);
      const connId = `up-${userInfo.address}-${forwarderAddress}-${Date.now()}`;
      const pc = createPeerConnection(forwarderAddress, connId, 'upstream');
      const dc = pc.createDataChannel('audio', { ordered: false, maxRetransmits: 0 });
      dc.binaryType = 'arraybuffer';

      const pcEntry = peerConnectionsRef.current.get(forwarderAddress);
      if (pcEntry) pcEntry.dc = dc;

      dc.onopen = () => {
        if (peerConnectionsRef.current.get(forwarderAddress)?.connId !== connId) return;
        debugLog('[GCall] Upstream DC opened to', forwarderAddress);
        upstreamDCRef.current = dc;
        // DC is now open — clear the relay rate-limiter entry so the relay is
        // available immediately if this DC closes later.
        relayLastSentRef.current.delete(forwarderAddress);
      };

      dc.onclose = () => {
        debugLog('[GCall] Upstream DC closed to', forwarderAddress);
        if (upstreamDCRef.current === dc) upstreamDCRef.current = null;
      };

      pc.onconnectionstatechange = () => {
        debugLog('[GCall] PC state (upstream →', forwarderAddress, '):', pc.connectionState);
      };

      pc.onicegatheringstatechange = () => {
        debugLog('[GCall] ICE gathering (upstream →', forwarderAddress, '):', pc.iceGatheringState);
      };

      pc.oniceconnectionstatechange = () => {
        debugLog('[GCall] ICE connection (upstream →', forwarderAddress, '):', pc.iceConnectionState);
      };

      // DataChannels are bidirectional: the forwarder sends audio (e.g. other
      // speakers' frames) back down through the same channel.  We must handle
      // those incoming frames here or they are silently discarded.
      dc.onmessage = (ev) => {
        handleIncomingAudioPacket(ev.data as ArrayBuffer, forwarderAddress);
      };

      const offer = await pc.createOffer();
      await pc.setLocalDescription(offer);

      const ts = Date.now();
      const sig = await signGroupCallFields(
        { type: 'GC_RTC_OFFER', roomId: roomIdRef.current, fromAddress: userInfo.address,
          toAddress: forwarderAddress, connId, fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
      ).catch(() => '');
      if (!sig) return; // signing failed — don't send unsigned RTC offer

      await window.groupCall.sendRtcSignal(
        roomIdRef.current, userInfo.address, forwarderAddress,
        'offer', offer.sdp, connId, sig, userInfo.publicKey ?? '', ts
      );
    },
    [createPeerConnection, userInfo]
  );

  /** Connect standby channels (as standby-forwarder, pre-established but idle). */
  const connectStandbyChannels = useCallback(
    async (topology: GroupTopology) => {
      if (!userInfo?.address) return;
      // Connect to root forwarder's backbone channel
      const rootAddr = topology.rootForwarder;
      if (rootAddr && rootAddr !== userInfo.address) {
        const connId = `standby-${userInfo.address}-${rootAddr}-${Date.now()}`;
        const pc = createPeerConnection(rootAddr, connId, 'backbone');
        const dc = pc.createDataChannel('standby-audio', { ordered: false, maxRetransmits: 0 });
        const pcEntry = peerConnectionsRef.current.get(rootAddr);
        if (pcEntry?.connId === connId) pcEntry.dc = dc;
        standbyDCRef.current = dc;

        const offer = await pc.createOffer();
        await pc.setLocalDescription(offer);

        const ts = Date.now();
        const sig = await signGroupCallFields(
          { type: 'GC_RTC_OFFER', roomId: roomIdRef.current, fromAddress: userInfo.address,
            toAddress: rootAddr, connId, fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
        ).catch(() => '');
        if (!sig) return; // signing failed — don't send unsigned RTC offer

        await window.groupCall.sendRtcSignal(
          roomIdRef.current, userInfo.address, rootAddr,
          'offer', offer.sdp, connId, sig, userInfo.publicKey ?? '', ts
        );
      }
    },
    [createPeerConnection, userInfo]
  );

  /** Forwarder: set up to accept incoming upstream connections from member. */
  const setupDownstreamChannel = useCallback(
    async (memberAddress: string) => {
      // We wait for the incoming offer via IPC event; handled in handleRtcSignal
    },
    []
  );

  /** Handle incoming RTC signal (offer/answer/ice). */
  const handleRtcSignal = useCallback(
    async (payload: any) => {
      const { type, fromAddress, connId, sdp, candidate } = payload;
      if (!userInfo?.address) return;
      debugLog('[GCall] handleRtcSignal type:', type, 'from:', fromAddress);

      if (type === 'offer') {
        const existing = peerConnectionsRef.current.get(fromAddress);
        if (existing && existing.connId !== connId && !isPeerConnectionInactive(existing)) {
          const existingTs = getConnIdTimestamp(existing.connId);
          const incomingTs = getConnIdTimestamp(connId);
          if (existingTs !== null && incomingTs !== null && incomingTs < existingTs) {
            debugLog('[GCall] Ignoring stale RTC offer from', fromAddress, 'connId:', connId, 'current:', existing.connId);
            return;
          }
        }

        // Create PC to accept the offer (downstream connection from member)
        const pc = createPeerConnection(fromAddress, connId, 'downstream');

        pc.onconnectionstatechange = () => {
          debugLog('[GCall] PC state (downstream ←', fromAddress, '):', pc.connectionState);
        };

        pc.oniceconnectionstatechange = () => {
          debugLog('[GCall] ICE connection (downstream ←', fromAddress, '):', pc.iceConnectionState);
        };

        pc.ondatachannel = (e) => {
          const dc = e.channel;
          dc.binaryType = 'arraybuffer';
          debugLog('[GCall] Downstream DC received from', fromAddress, '— channel:', dc.label);
          dc.onopen = () => {
            debugLog('[GCall] Downstream DC opened from', fromAddress);
            // Clear relay rate-limiter so the relay path is immediately available
            // if this DC closes again later.
            relayLastSentRef.current.delete(fromAddress);
          };
          dc.onclose = () => debugLog('[GCall] Downstream DC closed from', fromAddress);
          dc.onmessage = (ev) => {
            handleIncomingAudioPacket(ev.data as ArrayBuffer, fromAddress);
          };
          const pcEntry = peerConnectionsRef.current.get(fromAddress);
          if (pcEntry?.connId === connId) pcEntry.dc = dc;
        };

        await pc.setRemoteDescription({ type: 'offer', sdp });
        const answer = await pc.createAnswer();
        await pc.setLocalDescription(answer);

        const ts = Date.now();
        const sig = await signGroupCallFields(
          { type: 'GC_RTC_ANSWER', roomId: roomIdRef.current, fromAddress: userInfo.address,
            toAddress: fromAddress, connId, fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
        ).catch(() => '');
        if (!sig) return; // signing failed — don't send unsigned RTC answer

        await window.groupCall.sendRtcSignal(
          roomIdRef.current, userInfo.address, fromAddress,
          'answer', answer.sdp, connId, sig, userInfo.publicKey ?? '', ts
        );
      } else if (type === 'answer') {
        const pcEntry = peerConnectionsRef.current.get(fromAddress);
        if (!pcEntry || pcEntry.connId !== connId) {
          debugLog('[GCall] Ignoring stale RTC answer from', fromAddress, 'connId:', connId, 'current:', pcEntry?.connId ?? '(none)');
          return;
        }
        if (pcEntry) {
          await pcEntry.pc.setRemoteDescription({ type: 'answer', sdp });
        }
      } else if (type === 'ice') {
        const pcEntry = peerConnectionsRef.current.get(fromAddress);
        if (!pcEntry || pcEntry.connId !== connId) {
          debugLog('[GCall] Ignoring stale RTC ICE from', fromAddress, 'connId:', connId, 'current:', pcEntry?.connId ?? '(none)');
          return;
        }
        if (pcEntry && candidate) {
          try { await pcEntry.pc.addIceCandidate(candidate); } catch { /* ignore */ }
        }
      }
    },
    [createPeerConnection, getConnIdTimestamp, isPeerConnectionInactive, userInfo]
  );

  // ── Audio encode ──────────────────────────────────────────────────────────

  const callEpochRef = useRef<number>(0);

  const startAudioCapture = useCallback(async () => {
    debugLog('[GCall] startAudioCapture called — roomKey:', !!roomKeyRef.current, 'address:', userInfo?.address ?? '(none)');
    if (!userInfo?.address || !roomKeyRef.current) {
      debugWarn('[GCall] startAudioCapture guard failed — roomKey:', !!roomKeyRef.current, 'address:', userInfo?.address ?? '(none)');
      return;
    }
    callEpochRef.current = Date.now();

    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false });
      micStreamRef.current = stream;

      const ctx = new AudioContext({ sampleRate: OPUS_SAMPLE_RATE });
      audioContextRef.current = ctx;
      playbackWorkletModulePromiseRef.current = null;
      const source = ctx.createMediaStreamSource(stream);

      // Set up Opus encoder (runs on main thread but is fast — just packetizes)
      const encoder = new (window as any).AudioEncoder({
        output: (chunk: any) => {
          const frame = new Uint8Array(chunk.byteLength);
          chunk.copyTo(frame);
          sendEncodedFrame(frame);
        },
        error: (e: any) => console.error('[GCall] AudioEncoder error:', e),
      });

      encoder.configure({
        codec: 'opus',
        sampleRate: OPUS_SAMPLE_RATE,
        numberOfChannels: OPUS_CHANNELS,
        bitrate: OPUS_BITRATE,
      });

      encoderRef.current = encoder;

      // Load and instantiate the capture worklet (runs on the audio worklet thread)
      debugLog('[GCall] Loading capture worklet…');
      await ctx.audioWorklet.addModule('/worklets/capture-processor.js');
      await ctx.audioWorklet.addModule('/worklets/gcall-jitter-scheduler.js');
      debugLog('[GCall] Capture worklet loaded, AudioContext state:', ctx.state);
      playbackWorkletModulePromiseRef.current = ctx.audioWorklet.addModule('/worklets/group-playout-processor.js');
      const captureNode = new AudioWorkletNode(ctx, 'capture-processor');
      captureWorkletRef.current = captureNode;

      // Apply current mute state to the freshly created worklet
      captureNode.port.postMessage({ type: 'mute', muted: mutedRef.current });

      // Receive complete 960-sample Opus frames + VAD flag from the worklet thread
      captureNode.port.onmessage = (e) => {
        const { frame, vad } = e.data as { frame: Float32Array; vad: boolean };
        isSpeakingRef.current = vad;
        if (!encoderRef.current) return;
        const i16 = float32ToInt16(frame);
        const audioData = new (window as any).AudioData({
          format: 's16',
          sampleRate: OPUS_SAMPLE_RATE,
          numberOfFrames: OPUS_FRAME_SAMPLES,
          numberOfChannels: OPUS_CHANNELS,
          timestamp: performance.now() * 1000,
          data: i16,
        });
        encoderRef.current.encode(audioData);
        audioData.close();
      };

      // Connect source to captureNode for worklet processing, AND connect source
      // directly to a keep-alive gain node → destination.  This puts the mic SOURCE
      // itself inside the active rendering graph so Chrome delivers real microphone
      // samples to every connected output, including captureNode's inputs.
      //
      // Why not route captureNode → gain → destination instead?
      // captureNode never writes to outputs[0][0], so its output is all-zeros.
      // Chrome's AudioParam planner sees a constant-zero output and can mark the
      // entire upstream chain as "silent", stopping sample delivery to inputs[0][0].
      //
      // Why 0.0001 instead of 0?
      // A literal gain=0 AudioParam can be detected at the planner level and treated
      // as a "silent" path even before computing signal values.  0.0001 (-80 dB) is
      // physically inaudible but prevents that parameter-level zero optimisation.
      const keepAliveGain = ctx.createGain();
      keepAliveGain.gain.value = 0.0001;
      source.connect(captureNode);
      source.connect(keepAliveGain);
      keepAliveGain.connect(ctx.destination);

      // Jitter drain cadence tied to audio render clock (not setInterval).
      if (!jitterSchedulerNodeRef.current) {
        const jitterSched = new AudioWorkletNode(ctx, 'gcall-jitter-scheduler');
        jitterSched.port.onmessage = (ev: MessageEvent<{ type?: string }>) => {
          if (ev.data?.type !== 'tick') return;
          runJitterDrainTickRef.current();
        };
        const jitterSchedGain = ctx.createGain();
        jitterSchedGain.gain.value = 0.0001;
        jitterSched.connect(jitterSchedGain);
        jitterSchedGain.connect(ctx.destination);
        jitterSchedulerNodeRef.current = jitterSched;
      }

      debugLog('[GCall] Audio capture started — AudioContext state:', ctx.state);

    } catch (err) {
      console.error('[GCall] Audio capture failed:', err);
    }
  }, [userInfo?.address]);

  const ensurePlaybackWorkletLoaded = useCallback(async (): Promise<void> => {
    const ctx = audioContextRef.current;
    if (!ctx) return;
    if (!playbackWorkletModulePromiseRef.current) {
      playbackWorkletModulePromiseRef.current = ctx.audioWorklet.addModule('/worklets/group-playout-processor.js');
    }
    await playbackWorkletModulePromiseRef.current;
  }, []);

  const dispatchEncodedPacket = useCallback((packet: Uint8Array) => {
    if (!userInfo?.address || !roomIdRef.current || !roomKeyRef.current) return;
    if (upstreamDCRef.current?.readyState === 'open') {
      // Non-root: send to assigned forwarder
      upstreamDCRef.current.send(packet.buffer as ArrayBuffer);
    } else if (myRoleRef.current === 'root-forwarder' && topologyRef.current) {
      // Root-forwarder: no upstream DC; send own audio directly to all cluster members.
      // For members whose DC is not yet open, fall back to P2P relay so audio is never
      // silently dropped during WebRTC negotiation.
      const topo = topologyRef.current;
      for (const cluster of topo.clusters) {
        if (cluster.forwarder === userInfo.address) {
          for (const member of cluster.members) {
            if (member !== userInfo.address) {
              const pcEntry = peerConnectionsRef.current.get(member);
              if (pcEntry?.dc?.readyState === 'open') {
                pcEntry.dc.send(packet.buffer as ArrayBuffer);
              } else if (roomIdRef.current) {
                // DC not open yet — relay via P2P until WebRTC establishes.
                // Rate-limit to RELAY_MIN_INTERVAL_MS per peer to avoid flooding IPC
                // at 50 Hz during the 1–5 s negotiation window.
                const now = Date.now();
                if (now - (relayLastSentRef.current.get(member) ?? 0) >= RELAY_MIN_INTERVAL_MS) {
                  relayLastSentRef.current.set(member, now);
                  // Pass raw bytes over IPC; base64 conversion happens in the main process.
                  metricsRef.current.recordRelaySent();
                  window.groupCall.sendAudio(roomIdRef.current, member, packet).catch(() => {});
                }
              }
            }
          }
        }
      }
    } else {
      // Non-root and upstream DC not open yet — fall back to P2P relay via main process
      const topo = topologyRef.current;
      const target = topo ? findAssignedForwarder(userInfo.address, topo) : null;
      if (target && roomIdRef.current) {
        // Rate-limit to RELAY_MIN_INTERVAL_MS per peer to avoid flooding IPC
        // at 50 Hz during the 1–5 s WebRTC negotiation window.
        const now = Date.now();
        if (now - (relayLastSentRef.current.get(target) ?? 0) >= RELAY_MIN_INTERVAL_MS) {
          relayLastSentRef.current.set(target, now);
          // Pass raw bytes over IPC; base64 conversion happens in the main process.
          metricsRef.current.recordRelaySent();
          window.groupCall.sendAudio(roomIdRef.current, target, packet).catch(() => {});
        }
      }
    }
  }, [userInfo?.address]);

  const sendEncodedFrame = useCallback((opusFrame: Uint8Array) => {
    if (!roomKeyRef.current || !userInfo?.address) return;
    if (mutedRef.current) return; // mic is muted — drop frame
    if (seqRef.current === 0) {
      debugLog('[GCall] First encoded frame ready to send — role:', myRoleRef.current, 'upstreamDC:', upstreamDCRef.current?.readyState ?? 'none');
    }

    const seq = seqRef.current++ & 0xffff;
    const timestampMs = Date.now() - callEpochRef.current;

    if (decryptWorkerRef.current) {
      const frameBuffer =
        opusFrame.byteOffset === 0 && opusFrame.byteLength === opusFrame.buffer.byteLength
          ? opusFrame.buffer
          : opusFrame.slice().buffer;
      decryptWorkerRef.current.postMessage(
        {
          type: 'encrypt',
          id: encryptIdRef.current++,
          sourceAddr: userInfo.address,
          vad: isSpeakingRef.current,
          seq,
          timestampMs,
          opusFrame: frameBuffer,
        },
        [frameBuffer]
      );
      return;
    }

    dispatchEncodedPacket(
      encodePacket(
        userInfo.address,
        isSpeakingRef.current,
        seq,
        timestampMs,
        opusFrame,
        roomKeyRef.current
      )
    );
  }, [dispatchEncodedPacket, userInfo?.address]);

  // ── Audio decode ──────────────────────────────────────────────────────────

  const getOrCreateDecoder = useCallback((sourceAddr: string): AudioDecoder | null => {
    if (decoderMapRef.current.has(sourceAddr)) return decoderMapRef.current.get(sourceAddr)!;
    if (!audioContextRef.current) return null;
    debugLog('[GCall] Creating decoder + playback worklet for', sourceAddr.slice(0, 12));

    const ctx = audioContextRef.current;

    const setupPlayback = async (): Promise<AudioWorkletNode> => {
      debugLog('[GCall] Loading playback worklet for', sourceAddr.slice(0, 12));
      try {
        await ensurePlaybackWorkletLoaded();
        const playNode = new AudioWorkletNode(ctx, 'group-playout-processor', {
          processorOptions: { sourceAddr },
        } as AudioWorkletNodeOptions);
        playNode.port.onmessage = (e: MessageEvent) => {
          const d = e.data as {
            type?: string;
            bufferedMs?: number;
            outsideBand?: boolean;
            concealmentUsed?: boolean;
          };
          if (d?.type !== 'gcallPlayoutMetrics') return;
          if (typeof d.bufferedMs !== 'number') return;
          metricsRef.current.recordPlayoutMetricTick(d.bufferedMs, !!d.outsideBand);
          if (d.concealmentUsed) metricsRef.current.recordConcealmentTick(1);
        };
        playNode.connect(ctx.destination);
        playbackWorkletsRef.current.set(sourceAddr, playNode);
        updateMetricResourceCounts();
        debugLog('[GCall] Playback worklet ready for', sourceAddr.slice(0, 12), '— ctx state:', ctx.state);
        return playNode;
      } catch (err) {
        console.error('[GCall] Playback worklet FAILED for', sourceAddr.slice(0, 12), err);
        throw err;
      }
    };

    const playNodePromise = setupPlayback();

    let pcmCount = 0;
    const decoder = new (window as any).AudioDecoder({
      output: (audioData: any) => {
        pcmCount++;
        if (pcmCount <= 3) {
          debugLog('[GCall] AudioDecoder output PCM', pcmCount, 'frames:', audioData.numberOfFrames, 'for', sourceAddr.slice(0, 12));
        }
        const pcm = new Float32Array(audioData.numberOfFrames);
        audioData.copyTo(pcm, { planeIndex: 0, format: 'f32-planar' });
        audioData.close();
        const existing = playbackWorkletsRef.current.get(sourceAddr);
        if (existing) {
          existing.port.postMessage({ pcm }, [pcm.buffer]);
        } else {
          playNodePromise.then((node) => {
            node.port.postMessage({ pcm }, [pcm.buffer]);
          }).catch(() => {});
        }
      },
      error: (e: any) => console.error(`[GCall] AudioDecoder error for ${sourceAddr.slice(0, 12)}:`, e),
    });

    decoder.configure({ codec: 'opus', sampleRate: OPUS_SAMPLE_RATE, numberOfChannels: OPUS_CHANNELS });
    decoderMapRef.current.set(sourceAddr, decoder);
    updateMetricResourceCounts();
    return decoder;
  }, [ensurePlaybackWorkletLoaded, updateMetricResourceCounts]);

  // ── Incoming audio packet processing ──────────────────────────────────────

  const handleIncomingAudioPacket = useCallback((data: ArrayBuffer, _fromAddress: string) => {
    if (!roomKeyRef.current) return;
    const startedAt = performance.now();
    metricsRef.current.recordPacketReceived();

    const buf = new Uint8Array(data);

    // Parse the plaintext header synchronously so forwarding and speaker
    // tracking can happen immediately without waiting for crypto.
    const header = parsePacketHeader(buf);
    if (!header) {
      metricsRef.current.recordPacketDropped();
      metricsRef.current.recordIncomingPacketDuration(performance.now() - startedAt);
      debugWarn('[GCall] parsePacketHeader returned null — malformed packet, size:', buf.byteLength);
      return;
    }

    const { sourceAddr, vad, seq } = header;
    const myAddress = userInfo?.address ?? '';

    // Log first few packets per source so we can confirm the receive path works
    const jbExisting = jitterMapRef.current.get(sourceAddr);
    if (!jbExisting) {
      debugLog('[GCall] First packet from', sourceAddr.slice(0, 12), '— seq:', seq, 'vad:', vad);
    }

    // ── Active-speaker tracking ─────────────────────────────────────────────
    // Count currently-active speakers BEFORE adding sourceAddr so the gate
    // is based on the pre-existing set, not a set that was just mutated.
    const now = Date.now();
    const maxSpeakers = myRoleRef.current === 'root-forwarder'
      ? MAX_ACTIVE_SPEAKERS_GLOBAL
      : MAX_ACTIVE_SPEAKERS_LOCAL;

    if (vad) {
      lastVadTrueAtRef.current.set(sourceAddr, now);
      localSpeakersRef.current.set(sourceAddr, now);
      lastRecvAtRef.current.set(sourceAddr, performance.now());
    }

    const lastVadTrueAt = lastVadTrueAtRef.current.get(sourceAddr) ?? 0;
    const inForwardHangover =
      !vad && lastVadTrueAt > 0 && now - lastVadTrueAt < FORWARD_VAD_HANGOVER_MS;
    const effectiveVadForForward = vad || inForwardHangover;
    const isActiveSpeaker = evaluateActiveSpeaker(
      localSpeakersRef.current,
      sourceAddr,
      effectiveVadForForward,
      now,
      maxSpeakers,
      SPEAKER_GATE_WINDOW_MS
    );

    // If I'm a forwarder, forward to cluster members / root
    const role = myRoleRef.current;
    const topo = topologyRef.current;

    if ((role === 'cluster-forwarder' || role === 'root-forwarder') && topo) {
      // Forward when admission allows, including VAD hangover (brief gaps between words).
      if (isActiveSpeaker) {
        const forwarded = forwardPacketForRole(
          role,
          topo,
          myAddress,
          sourceAddr,
          data,
          sendPacketToPeer
        );
        if (forwarded > 0) metricsRef.current.recordPacketForwarded(forwarded);
      }
      // Fall through to local playback — the root/cluster forwarder is also a
      // participant in the call and must hear other speakers.  Forwarding and
      // local decoding are independent operations.
    }

    // Don't decrypt or play own audio.
    if (sourceAddr === myAddress) {
      metricsRef.current.recordIncomingPacketDuration(performance.now() - startedAt);
      return;
    }

    // ── Off-thread decryption ───────────────────────────────────────────────
    // Post the packet to the Worker for nacl.secretbox.open so the main thread
    // is not blocked by crypto at 50 Hz × N peers.  The Worker posts back the
    // decrypted opusFrame which is then pushed to the jitter buffer.
    if (decryptWorkerRef.current) {
      // Copy the buffer — the original `data` may still be in use by DataChannel
      // forwarding above, and ArrayBuffer transfer would detach it.
      const bufCopy = buf.slice().buffer;
      decryptWorkerRef.current.postMessage(
        { type: 'decrypt', id: decryptIdRef.current++, buffer: bufCopy },
        [bufCopy]
      );
    } else {
      // Fallback: synchronous decryption on main thread when worker is unavailable.
      const decoded = decodePacket(buf, roomKeyRef.current);
      if (!decoded) {
        metricsRef.current.recordPacketDropped();
        metricsRef.current.recordIncomingPacketDuration(performance.now() - startedAt);
        debugWarn('[GCall] decodePacket (sync fallback) failed — size:', buf.byteLength);
        return;
      }
      let jb = jitterMapRef.current.get(decoded.sourceAddr);
      if (!jb) {
        jb = new JitterBuffer();
        jitterMapRef.current.set(decoded.sourceAddr, jb);
        updateMetricResourceCounts();
      }
      jb.push(decoded.seq, decoded.opusFrame);
      recordInterArrivalForPlayout(decoded.sourceAddr);
      if (jb.hasReadyFrame()) {
        activeJitterSourcesRef.current.add(decoded.sourceAddr);
      }
    }
    metricsRef.current.recordIncomingPacketDuration(performance.now() - startedAt);
  }, [recordInterArrivalForPlayout, sendPacketToPeer, updateMetricResourceCounts, userInfo?.address]);

  /** One drain step: invoked from gcall-jitter-scheduler AudioWorklet (~20ms audio clock).
   *  postMessage timing can still jitter on the main thread; deeper jitter buffer + playback
   *  ring absorb variance. */
  const runJitterDrainTick = useCallback(() => {
    const tickStartedAt = performance.now();
    for (const addr of [...activeJitterSourcesRef.current]) {
      const jb = jitterMapRef.current.get(addr);
      if (!jb || !jb.hasReadyFrame()) {
        if (jb) metricsRef.current.recordJitterUnderrun();
        activeJitterSourcesRef.current.delete(addr);
        continue;
      }
      let missedThisTick = 0;
      let burst = 0;
      while (burst < JITTER_DECODE_BURST_MAX && jb.hasReadyFrame()) {
        const frame = jb.pop();
        if (!frame) break;
        missedThisTick += jb.consumePendingMissedFrames();
        burst++;
        if (!jitterFirstDrainLoggedRef.current) {
          jitterFirstDrainLoggedRef.current = true;
          debugLog('[GCall] Jitter drain first pop for', addr.slice(0, 12), '— frame bytes:', frame.byteLength);
          debugLog('[GCall] Decoder input frame view for', addr.slice(0, 12), {
            byteOffset: frame.byteOffset,
            byteLength: frame.byteLength,
            bufferByteLength: frame.buffer.byteLength,
          });
        }
        const decoder = getOrCreateDecoder(addr);
        if (decoder && decoder.state !== 'closed') {
          try {
            const chunk = new (window as any).EncodedAudioChunk({
              type: 'key',
              timestamp: performance.now() * 1000,
              data: frame,
            });
            decoder.decode(chunk);
          } catch (e) {
            metricsRef.current.recordPacketDropped();
            debugWarn('[GCall] decoder.decode threw:', e);
          }
        } else if (!decoder) {
          debugWarn('[GCall] getOrCreateDecoder returned null for', addr.slice(0, 12));
        }
      }
      if (missedThisTick > 0) {
        metricsRef.current.recordMissingFrames(missedThisTick);
        lastDrainMissedRef.current.set(addr, (lastDrainMissedRef.current.get(addr) ?? 0) + missedThisTick);
      }
      if (!jb.hasReadyFrame()) {
        activeJitterSourcesRef.current.delete(addr);
      }
    }

    tickAdaptivePlayoutTargets();

    // Throttle React state updates to ~200ms (10 scheduler ticks ≈ 10 × 20ms).
    jitterDrainReactTickCountRef.current++;
    if (jitterDrainReactTickCountRef.current >= 10) {
      jitterDrainReactTickCountRef.current = 0;
      const tickNow = Date.now();
      const speakers = collectActiveSpeakers(
        localSpeakersRef.current,
        tickNow,
        ACTIVE_SPEAKER_WINDOW_MS,
        MAX_ACTIVE_SPEAKERS_GLOBAL
      );
      setActiveSpeakers((prev) => (sameAddressList(prev, speakers) ? prev : speakers));
      setParticipants((prev) => reconcileParticipantSpeaking(prev, speakers));
    }
    metricsRef.current.recordJitterTickDuration(performance.now() - tickStartedAt);
  }, [getOrCreateDecoder, tickAdaptivePlayoutTargets]);

  runJitterDrainTickRef.current = runJitterDrainTick;

  // ── Room key distribution ─────────────────────────────────────────────────

  const distributeRoomKey = useCallback(async (
    key: Uint8Array,
    recipients?: ReadonlyMap<string, { publicKey: string }>,
  ) => {
    if (!userInfo?.address) return;
    const myAddr = userInfo.address;
    const roster = recipients ?? participantsRef.current;
    debugLog('[GCall] distributeRoomKey — recipients:', [...roster.keys()].filter((a) => a !== myAddr));

    for (const [addr, { publicKey }] of roster) {
      if (addr === myAddr) continue;

      // Encrypt key for this participant using their Ed25519 public key.
      // Convert Ed25519 public key to Curve25519 for nacl.box, then use an
      // ephemeral keypair so the recipient can compute the same shared secret.
      try {
        const recipientPkBytes = base58DecodeRenderer(publicKey);
        const recipientCurve25519PK = ed2curve.convertPublicKey(recipientPkBytes);
        const ephemeralKP = naclApi.box.keyPair();
        const sharedKey = naclApi.box.before(recipientCurve25519PK, ephemeralKP.secretKey);
        const nonce = naclApi.randomBytes(24);
        const ciphertext = naclApi.box.after(key, nonce, sharedKey);

        // Wire format: [ephemeralPK (32)] + [nonce (24)] + [ciphertext]
        const combined = new Uint8Array(32 + 24 + ciphertext.length);
        combined.set(ephemeralKP.publicKey, 0);
        combined.set(nonce, 32);
        combined.set(ciphertext, 56);

        const b64 = uint8ToBase64(combined);
        const ts = Date.now();
      const sig = await signGroupCallFields(
        { type: 'GC_KEY', roomId: roomIdRef.current,
          toAddress: addr, fromAddress: myAddr,
          fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
      ).catch(() => '');
        if (!sig) { debugWarn(`[GCall] Signing failed for GC_KEY to ${addr}`); continue; }
        await window.groupCall.sendKey(
          roomIdRef.current, addr, b64, myAddr, sig, userInfo.publicKey ?? '', ts
        );
      } catch (e) {
        debugWarn(`[GCall] Failed to encrypt key for ${addr}:`, e);
      }
    }
  }, [userInfo]);

  /** Handle incoming room key. */
  const handleRoomKey = useCallback(async (payload: { encryptedKey: string }) => {
    debugLog('[GCall] handleRoomKey called — encryptedKey length:', payload.encryptedKey?.length ?? 0);
    try {
      // Wire format: [ephemeralPK (32)] + [nonce (24)] + [ciphertext]
      const combined = base64ToUint8(payload.encryptedKey);
      const ephemeralPKb64  = uint8ToBase64(combined.slice(0, 32));
      const nonceb64        = uint8ToBase64(combined.slice(32, 56));
      const ciphertextb64   = uint8ToBase64(combined.slice(56));

      const result = await (window as any).sendMessage(
        'decryptBoxWithMyKey',
        { ephemeralPublicKey: ephemeralPKb64, nonce: nonceb64, ciphertext: ciphertextb64 },
        10_000
      );
      debugLog('[GCall] decryptBoxWithMyKey result ok:', !!result?.decryptedKey);
      if (result?.decryptedKey) {
        roomKeyRef.current = Uint8Array.from(atob(result.decryptedKey), (c) => c.charCodeAt(0));
        syncDecryptWorkerRoomKey(roomKeyRef.current);
        debugLog('[GCall] Room key set (', roomKeyRef.current.length, 'bytes), captureWorklet exists:', !!captureWorkletRef.current);
        // Non-root-forwarder: start audio now that we have the shared key
        if (!captureWorkletRef.current) {
          startAudioCapture();
        }
      }
    } catch (e) {
      debugWarn('[GCall] Failed to decrypt room key:', e);
    }
  }, [startAudioCapture, syncDecryptWorkerRoomKey]);

  // ── Decrypt Worker lifecycle ──────────────────────────────────────────────

  /** Create the off-thread decrypt Worker and attach its message handler.
   *  Called at join time; the Worker is terminated in cleanup(). */
  const setupDecryptWorker = useCallback(() => {
    if (decryptWorkerRef.current) return; // already running
    const worker = new AudioDecryptWorker();
    decryptWorkerRef.current = worker;
    decryptIdRef.current = 0;
    encryptIdRef.current = 0;
    syncDecryptWorkerRoomKey(roomKeyRef.current);

    worker.onmessage = (e: MessageEvent<{
      type: 'result' | 'encryptResult';
      id: number;
      decoded?: {
        sourceAddr: string;
        vad: boolean;
        seq: number;
        timestampMs: number;
        opusFrame: ArrayBuffer;
      } | null;
      packet?: ArrayBuffer | null;
    }>) => {
      if (e.data.type === 'encryptResult') {
        if (e.data.packet) {
          dispatchEncodedPacket(new Uint8Array(e.data.packet));
        }
        return;
      }
      if (e.data.type !== 'result' || !e.data.decoded) return;
      const { sourceAddr, seq, opusFrame } = e.data.decoded;
      let jb = jitterMapRef.current.get(sourceAddr);
      if (!jb) {
        jb = new JitterBuffer();
        jitterMapRef.current.set(sourceAddr, jb);
        updateMetricResourceCounts();
      }
      jb.push(seq, new Uint8Array(opusFrame));
      recordInterArrivalForPlayout(sourceAddr);
      if (jb.hasReadyFrame()) {
        activeJitterSourcesRef.current.add(sourceAddr);
      }
      metricsRef.current.recordPacketDecoded();
    };

    worker.onerror = (err) => {
      console.error('[GCall] AudioDecryptWorker error:', err);
    };
  }, [dispatchEncodedPacket, recordInterArrivalForPlayout, syncDecryptWorkerRoomKey, updateMetricResourceCounts]);

  // ── Join / Leave ──────────────────────────────────────────────────────────

  const joinGroupCall = useCallback(async (roomId: string, chatId: string) => {
    if (!userInfo?.address || !userInfo.publicKey) return;
    if (roomState !== 'idle') return;
    debugLog('[GCall] joinGroupCall — roomId:', roomId, 'address:', userInfo.address);

    roomIdRef.current = roomId;
    chatIdRef.current = chatId;
    setRoomState('joining');
    metricsRef.current.reset();
    metricsRef.current.setRole('participant');
    flushMetrics();

    // Register local address with main process
    await window.groupCall.setLocalAddresses([userInfo.address]);

    const jbuf = new Uint32Array(1);
    crypto.getRandomValues(jbuf);
    const joinGeneration = jbuf[0]! >>> 0;
    joinGenerationRef.current = joinGeneration;

    // Sign join envelope
    const ts = Date.now();
    const sig = await signGroupCallFields(
      {
        type: 'GC_JOIN',
        roomId,
        chatId,
        fromAddress: userInfo.address,
        fromPublicKey: userInfo.publicKey,
        timestamp: ts,
        joinGeneration,
      }
    ).catch(() => '');
    if (!sig) {
      debugWarn('[GCall] Signing failed for GC_JOIN — aborting join');
      joinGenerationRef.current = null;
      setRoomState('idle');
      return;
    }

    // Add self to participant list
    participantsRef.current.set(userInfo.address, {
      publicKey: userInfo.publicKey,
      lastJoinTs: ts,
      joinGeneration,
    });
    setParticipants([{ address: userInfo.address, publicKey: userInfo.publicKey, speaking: false, role: 'participant' }]);

    // Send join to network
    await window.groupCall.join(
      roomId,
      chatId,
      userInfo.address,
      sig,
      userInfo.publicKey,
      ts,
      joinGeneration
    );

    setRoomState('connected');

    // Reset the root-heartbeat timestamp to now so the standby-forwarder timeout
    // check doesn't misfire immediately if the hook was mounted long before joining.
    lastRootHeartbeatRef.current = Date.now();

    // Room key and audio capture are deferred until the first topology is
    // computed (in participant-joined).  Only the elected root-forwarder
    // generates and distributes the key; others wait for GC_KEY.
    setupDecryptWorker();
    startForwarderTimeoutCheck();
    startMetricsFlushLoop();
  }, [flushMetrics, roomState, setupDecryptWorker, startMetricsFlushLoop, userInfo]);

  const leaveGroupCall = useCallback(async () => {
    if (!userInfo?.address || roomState === 'idle') return;

    // Sign leave envelope
    const ts = Date.now();
    const sig = await signGroupCallFields(
      { type: 'GC_LEAVE', roomId: roomIdRef.current,
        fromAddress: userInfo.address,
        fromPublicKey: userInfo.publicKey ?? '', timestamp: ts }
    ).catch(() => '');

    // Always clean up locally; only broadcast if signing succeeded
    if (sig) {
      await window.groupCall.leave(
        roomIdRef.current, userInfo.address, sig, userInfo.publicKey ?? '', ts
      );
    }

    cleanup();
  }, [userInfo, roomState]);

  const startForwarderTimeoutCheck = useCallback(() => {
    if (forwarderTimeoutCheckRef.current) clearInterval(forwarderTimeoutCheckRef.current);
    forwarderTimeoutCheckRef.current = setInterval(checkForwarderTimeout, FORWARDER_TIMEOUT_CHECK_MS);
  }, [checkForwarderTimeout]);

  // ── Cleanup ───────────────────────────────────────────────────────────────

  const cleanup = useCallback(() => {
    window.groupCall?.setLocalAddresses([]).catch(() => {});
    if (jitterSchedulerNodeRef.current) {
      try {
        jitterSchedulerNodeRef.current.port.onmessage = null;
        jitterSchedulerNodeRef.current.disconnect();
      } catch {
        /* ignore */
      }
      jitterSchedulerNodeRef.current = null;
    }
    jitterDrainReactTickCountRef.current = 0;
    jitterFirstDrainLoggedRef.current = false;
    lastVadTrueAtRef.current.clear();
    if (topologyHeartbeatTimerRef.current) { clearInterval(topologyHeartbeatTimerRef.current); topologyHeartbeatTimerRef.current = null; }
    if (promotionTimerRef.current) { clearTimeout(promotionTimerRef.current); promotionTimerRef.current = null; }
    if (forwarderTimeoutCheckRef.current) { clearInterval(forwarderTimeoutCheckRef.current); forwarderTimeoutCheckRef.current = null; }
    stopMetricsFlushLoop();

    // Stop audio
    if (captureWorkletRef.current) {
      captureWorkletRef.current.disconnect();
      captureWorkletRef.current = null;
    }
    for (const [, node] of playbackWorkletsRef.current) {
      node.disconnect();
    }
    playbackWorkletsRef.current.clear();
    playbackWorkletModulePromiseRef.current = null;
    if (micStreamRef.current) {
      micStreamRef.current.getTracks().forEach((t) => t.stop());
      micStreamRef.current = null;
    }
    if (encoderRef.current && encoderRef.current.state !== 'closed') {
      encoderRef.current.close();
      encoderRef.current = null;
    }
    if (audioContextRef.current && audioContextRef.current.state !== 'closed') {
      audioContextRef.current.close();
      audioContextRef.current = null;
    }

    // Close decoders
    for (const [, dec] of decoderMapRef.current) {
      try { if (dec.state !== 'closed') dec.close(); } catch { /* ignore */ }
    }
    decoderMapRef.current.clear();
    jitterMapRef.current.clear();
    activeJitterSourcesRef.current.clear();
    lastRecvAtRef.current.clear();

    // Close peer connections
    for (const peerAddress of [...peerConnectionsRef.current.keys()]) {
      closePeerConnection(peerAddress);
    }

    upstreamDCRef.current = null;
    standbyDCRef.current = null;
    relayLastSentRef.current.clear();

    // Terminate the decrypt Worker
    if (decryptWorkerRef.current) {
      syncDecryptWorkerRoomKey(null);
      decryptWorkerRef.current.terminate();
      decryptWorkerRef.current = null;
    }
    decryptIdRef.current = 0;

    // Reset state
    roomKeyRef.current = null;
    topologyRef.current = null;
    localEpochRef.current = 0;
    roomIdRef.current = '';
    chatIdRef.current = '';
    participantsRef.current = new Map();
    seqRef.current = 0;
    topologyAsyncGenRef.current = 0;
    joinGenerationRef.current = null;
    localSpeakersRef.current.clear();
    metricsRef.current.reset();
    metricsRef.current.setRole('participant');

    setRoomState('idle');
    setParticipants([]);
    setMyRole('participant');
    setActiveSpeakers([]);
    flushMetrics();
  }, [closePeerConnection, flushMetrics, stopMetricsFlushLoop, syncDecryptWorkerRoomKey]);

  // ── IPC event subscription ─────────────────────────────────────────────────

  useEffect(() => {
    const shouldSubscribe = Boolean(window.groupCall) && (uiActive || roomState !== 'idle');
    if (!shouldSubscribe || !window.groupCall) {
      unsubscribeRef.current?.();
      unsubscribeRef.current = null;
      return;
    }

    const unsub = window.groupCall.onEvent((event: string, payload: any) => {
      if (event === 'gcall:participant-joined') {
        const { roomId, address, publicKey } = payload;
        const joinTs = Number(payload.timestamp);
        const incomingGen =
          typeof payload.joinGeneration === 'number' && Number.isFinite(payload.joinGeneration)
            ? payload.joinGeneration
            : undefined;
        if (roomId !== roomIdRef.current) return;
        if (!Number.isFinite(joinTs)) return;
        // Self is already in the roster from joinGroupCall; relayed GC_JOIN must not run rejoin teardown.
        if (address === userInfo?.address) return;

        const wasExisting = participantsRef.current.has(address);
        const existing = participantsRef.current.get(address);
        // Same or older GC_JOIN (relay duplicate) — ignore to avoid topology churn.
        if (existing && joinTs <= existing.lastJoinTs) return;

        // Same session mesh re-announce: newer ts, same publicKey, compatible joinGeneration.
        if (existing && joinTs > existing.lastJoinTs && publicKey === existing.publicKey) {
          const genMismatch =
            existing.joinGeneration !== undefined &&
            incomingGen !== undefined &&
            incomingGen !== existing.joinGeneration;
          if (!genMismatch) {
            participantsRef.current.set(address, {
              publicKey,
              lastJoinTs: joinTs,
              ...(incomingGen !== undefined || existing.joinGeneration !== undefined
                ? { joinGeneration: incomingGen ?? existing.joinGeneration }
                : {}),
            });
            return;
          }
          participantsRef.current.set(address, {
            publicKey,
            lastJoinTs: joinTs,
            joinGeneration: incomingGen,
          });
          closePeerConnection(address);
          disposeParticipantAudio(address);
          setParticipants((prev) => {
            const i = prev.findIndex((p) => p.address === address);
            if (i === -1) {
              return [...prev, { address, publicKey, speaking: false, role: 'participant' }];
            }
            return prev.map((p) => (p.address === address ? { ...p, publicKey } : p));
          });
        } else if (!wasExisting) {
          participantsRef.current.set(address, {
            publicKey,
            lastJoinTs: joinTs,
            ...(incomingGen !== undefined ? { joinGeneration: incomingGen } : {}),
          });
          setParticipants((prev) => {
            if (prev.some((p) => p.address === address)) return prev;
            return [...prev, { address, publicKey, speaking: false, role: 'participant' }];
          });
        } else if (existing && publicKey !== existing.publicKey) {
          participantsRef.current.set(address, {
            publicKey,
            lastJoinTs: joinTs,
            ...(incomingGen !== undefined ? { joinGeneration: incomingGen } : {}),
          });
          closePeerConnection(address);
          disposeParticipantAudio(address);
          setParticipants((prev) => {
            const i = prev.findIndex((p) => p.address === address);
            if (i === -1) {
              return [...prev, { address, publicKey, speaking: false, role: 'participant' }];
            }
            return prev.map((p) => (p.address === address ? { ...p, publicKey } : p));
          });
        }

        // Re-announce ourselves to the newly discovered peer so they learn about us.
        // Peers who joined before the flood may have missed our GC_JOIN; re-sends fix that.
        if (address !== userInfo?.address && userInfo?.address && userInfo?.publicKey) {
          const jg = joinGenerationRef.current;
          if (jg !== null) {
            const rts = Date.now();
            signGroupCallFields({
              type: 'GC_JOIN',
              roomId,
              chatId: chatIdRef.current,
              fromAddress: userInfo.address,
              fromPublicKey: userInfo.publicKey,
              timestamp: rts,
              joinGeneration: jg,
            })
              .then((rsig) => {
                if (rsig) {
                  window.groupCall.join(
                    roomId,
                    chatIdRef.current,
                    userInfo.address,
                    rsig,
                    userInfo.publicKey!,
                    rts,
                    jg
                  );
                }
              })
              .catch(() => {});
          }
        }

        const myGen = ++topologyAsyncGenRef.current;
        void (async () => {
          const fresh = [...participantsRef.current.keys()];
          if (fresh.length === 0) return;
          const sorted = await computeElectionOrder(fresh, roomIdRef.current);
          if (myGen !== topologyAsyncGenRef.current) return;
          const newTopo = buildTopology(sorted, localEpochRef.current + 1);
          const prevRoot = topologyRef.current?.rootForwarder;
          applyTopology(newTopo);

          const myAddress = userInfo?.address ?? '';
          // Only the elected root-forwarder is the key authority.
          isInitiatorRef.current = myAddress === newTopo.rootForwarder;
          debugLog(
            '[GCall] Election result — me:',
            myAddress,
            'rootForwarder:',
            newTopo.rootForwarder,
            'isInitiator:',
            isInitiatorRef.current,
            'hasKey:',
            !!roomKeyRef.current
          );

          // Root handoff: drop media key so handleRoomKey accepts the new root's GC_KEY.
          // Stable non-root + unchanged root: keep key (avoids racing participant-joined vs GC_KEY).
          if (
            !isInitiatorRef.current &&
            prevRoot !== undefined &&
            prevRoot !== newTopo.rootForwarder
          ) {
            roomKeyRef.current = null;
            syncDecryptWorkerRoomKey(null);
          }

          if (isInitiatorRef.current && !roomKeyRef.current) {
            debugLog('[GCall] Generating room key and starting audio capture');
            const newKey = naclApi.randomBytes(32);
            roomKeyRef.current = newKey;
            syncDecryptWorkerRoomKey(newKey);
            startAudioCapture();
            void distributeRoomKey(newKey);
          } else if (isInitiatorRef.current && roomKeyRef.current) {
            debugLog('[GCall] Already have key — distributing to full roster after election');
            void distributeRoomKey(roomKeyRef.current);
          }
        })();
      }

      if (event === 'gcall:participant-left') {
        const { roomId, address } = payload;
        if (roomId !== roomIdRef.current) return;
        closePeerConnection(address);
        disposeParticipantAudio(address);
        participantsRef.current.delete(address);
        setActiveSpeakers((prev) => prev.filter((speaker) => speaker !== address));
        setParticipants((prev) => prev.filter((p) => p.address !== address));

        const addrs = [...participantsRef.current.keys()];
        if (addrs.length === 0) return;

        const myGen = ++topologyAsyncGenRef.current;
        void (async () => {
          const fresh = [...participantsRef.current.keys()];
          if (fresh.length === 0) return;
          const sorted = await computeElectionOrder(fresh, roomIdRef.current);
          if (myGen !== topologyAsyncGenRef.current) return;
          const newTopo = buildTopology(sorted, localEpochRef.current + 1);
          applyTopology(newTopo);

          const myAddress = userInfo?.address ?? '';
          isInitiatorRef.current = myAddress === newTopo.rootForwarder;
          if (isInitiatorRef.current && roomKeyRef.current) {
            const newKey = naclApi.randomBytes(32);
            roomKeyRef.current = newKey;
            syncDecryptWorkerRoomKey(newKey);
            void distributeRoomKey(newKey);
          }
        })();
      }

      if (event === 'gcall:topology') {
        const topo = payload as GroupTopology & { roomId: string };
        if (topo.roomId !== roomIdRef.current) return;
        lastRootHeartbeatRef.current = Date.now();
        applyTopology(topo);
      }

      if (event === 'gcall:heartbeat') {
        const { roomId } = payload as { roomId: string };
        if (roomId !== roomIdRef.current) return;
        lastRootHeartbeatRef.current = Date.now();
      }

      if (event === 'gcall:audio') {
        const { data } = payload as { data: Uint8Array };
        // P2P relay fallback — main process already decoded base64 to binary Buffer,
        // which arrives here as a Uint8Array via structured clone. No atob needed.
        metricsRef.current.recordRelayReceived();
        const relayBuffer =
          data.byteOffset === 0 && data.byteLength === data.buffer.byteLength
            ? data.buffer
            : data.slice().buffer;
        handleIncomingAudioPacket(relayBuffer as ArrayBuffer, '');
      }

      if (event === 'gcall:key') {
        handleRoomKey(payload);
      }

      if (event === 'gcall:rtc-signal') {
        handleRtcSignal(payload);
      }
    });

    unsubscribeRef.current = unsub;
    return () => { unsub(); unsubscribeRef.current = null; };
  }, [
    applyTopology,
    closePeerConnection,
    disposeParticipantAudio,
    distributeRoomKey,
    handleIncomingAudioPacket,
    handleRoomKey,
    handleRtcSignal,
    roomState,
    startAudioCapture,
    syncDecryptWorkerRoomKey,
    uiActive,
    userInfo?.address,
  ]);

  // Cleanup only on real unmount. Do NOT key this on `cleanup` — when `cleanup`'s identity
  // changes (e.g. flushMetrics used to depend on roomState), React would run the previous
  // teardown and call cleanup() mid-session, clearing groupCall local addresses and killing the call.
  const cleanupRef = useRef(cleanup);
  cleanupRef.current = cleanup;
  useEffect(
    () => () => {
      cleanupRef.current();
    },
    []
  );

  return {
    roomState,
    participants,
    myRole,
    activeSpeakers,
    metrics,
    topologyLabel,
    joinGroupCall,
    leaveGroupCall,
    setMuted: (m: boolean) => {
      mutedRef.current = m;
      captureWorkletRef.current?.port.postMessage({ type: 'mute', muted: m });
    },
    roomId: roomIdRef.current,
  };
}

// ── Base58 decode helper (renderer side) ──────────────────────────────────────

function base58DecodeRenderer(str: string): Uint8Array {
  const ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
  const bytes: number[] = [];
  let num = BigInt(0);
  for (const char of str) {
    const idx = ALPHABET.indexOf(char);
    if (idx === -1) throw new Error('Invalid base58 char');
    num = num * BigInt(58) + BigInt(idx);
  }
  let hex = num.toString(16);
  if (hex.length % 2) hex = '0' + hex;
  for (let i = 0; i < hex.length; i += 2) bytes.push(parseInt(hex.slice(i, i + 2), 16));
  return new Uint8Array(bytes);
}
